### ISSUE TITLE
`string.length` returns the number of bytes, not length of a string

### ISSUE THREAD

**Issue by euank** [tweag/nickel#1003]
**Describe the bug**

Most string functions, like `string.split`, `string.chars`, etc, operate on actual unicode characters.

`string.length` seems to operate on number of bytes.

**To Reproduce**

```
nickel> string.length "👨‍❤️‍💋‍👨"
27

nickel> string.length "四字熟語"
12
```

**Expected behavior**

I believe those should be 1 and 4 respectively.

**Environment**
 - NixOS something or other
 - current master, 33caa639

**Additional context**

I'm happy to implement a fix if the expected behavior above is what we want! I think it is, but it's possible I'm missing some reason here.

**Comment by euank** [comment]
A similar issue occurs for substring.
I'm happy to file a separate issue for this one if you'd like!

Basically:

```
nickel> string.substring 3 6 "子猫"
"猫"

nickel> string.substring 0 1 "子猫"
error: substring: index out of bounds. Expected the 3rd argument (end) to be between 1 and 6, got 1

nickel> string.substring 1 2 "子猫"
error: substring: index out of bounds. Expected the 2nd argument (start) to be between 0 and 6, got 1
```

Kinda confusing error there too.

**Comment by aspiwack** [comment]
Thanks for raising this.

Length of Unicode strings is always a thorny subject. I don't know the encoding for CJK characters, but I imagine that it's mostly 1 code point per glyph, so it's alright. But I don't know that there are good ways to count glyphs in general, is there? Then you have to decide on a normalisation and count code points in said normalised form, probably. Or maybe just count code points in the unnormalised string that you get as input?

At any rate, I agree that counting bytes is probably not what we want.

**Comment by matthew-healy** [comment]
If we want to count code points then we can just replace [this line](https://github.com/tweag/nickel/blob/master/src/eval/operation.rs#L988) with 

```rust
Term::Num(s.chars().count() as f64)
```

In the second example that gives a length of `4` as expected, though in the first example it gives a length of `8`. I know Swift does some magick while calculating string sizes & does actually return `1` for the first example, but I haven't looked into how in any detail. 

Personally I think it'd be fine to just count code points for now & go to the extra effort later if it turns out knowing the "visual" size of emoji is critical to some kind of configuration wrangilng we want to support. :grin:

**Comment by aspiwack** [comment]
It's not just emojis, though. I'd guess, for instance, that ‘ő’ (Hungarian) is not a single code point in any encoding. And I'd be very surprised if ‘ế’ (Vietnamese) was. On the other hand ‘é’ (French) can be a single code point, but need not be, depending on the normalisation.

At any rate, counting code points already improves on the situation. Though we have to think about stability.

**Comment by matthew-healy** [comment]
All fair points! It looks like [this crate](https://crates.io/crates/unicode-segmentation) can also count grapheme clusters which might give us the desired counts in all/most cases, so that's another option to look into when we fix this.

**Comment by aspiwack** [comment]
The crate looks well-maintained, and reasonably used. Also anything with Alex Crichton as a maintainer is likely to be a reasonable dependency. Sounds like a reasonable plan to me.

**Comment by matthew-healy** [comment]
I've opened a PR (#1005) which makes the `%str_length%` primitive return the number of extended grapheme clusters in the string, which results in the desired behaviour. However, I think it probably now makes sense to go through the rest of the string operations we expose, many of which currently work with code points, and have them instead work with grapheme clusters. I'll open a separate issue for that.
