### ISSUE TITLE
stdlib string functions should work on extended grapheme clusters

### ISSUE THREAD

**Issue by matthew-healy** [tweag/nickel#1007]
Once #1005 is merged, `string.length` will count the number of extended grapheme clusters in a (UTF-8) string. This means that characters comprised of multiple code points, but still representing a "single character" are counted as one character for the purpose of this function.

However, other standard library string functions (or more accurately, the string primops) still operate on code points, e.g. `string.substring`, `string.split`, etc. 

In general, this issue proposes that we should consider the extended grapheme cluster to be the smallest unit of Nickel strings, and all string manipulation functionality should be updated accordingly.

**Comment by matthew-healy** [comment]
Noting here that we'll remove `string.codepoint` and `string.from_codepoint` as part of this work as:

1. they break the extended grapheme cluster abstraction, and
2. there are no similar functions for strings in Nix
3. we don't have any concrete use cases for them.

**Comment by matthew-healy** [comment]
I just merged #1200 which partly solves this. The remaining work is around the behaviour of regex search functions, which currently *do* break up grapheme clusters.

**Comment by yannham** [comment]
@matthew-healy I don't know if we will have time to finish that before 1.0. Anyway, I think the most important is already here: Unicode-aware regexps are hopefully more of a edge use-case. In the meantime, we probably want to update the documentation of regex-related functions with a big warning saying that those aren't (yet) unicode aware.

**Comment by matthew-healy** [comment]
Yes, very fair. I'll try to spend some time updating the docs later today, as I'm away from tomorrow until Wednesday.

**Comment by yannham** [comment]
Removing from 1.0 milestone because we agreed that #1200 + #1212 are enough for 1.0, while not strictly closing this issue either.
