### ISSUE TITLE
Cannot use multiline string

### ISSUE THREAD

**Issue by pleshevskiy** [tweag/nickel#1032]
**Describe the bug**
Error appears when using a multi-line string with `nickel` cli.

**To Reproduce**

```
➜ nickel repl
nickel> m%"hello world"%m
error: unbound identifier
  ┌─ repl-input-0:1:17
  │
1 │ m%"hello world"%m
  │                 ^ this identifier is unbound
```

**Expected behavior**
```
➜ nickel repl
nickel> m%"hello world"%m
"hello world"
```

**Environment**
 - OS name + version: NixOS 23.05.20221222.652e92b (Stoat) x86_64
 - Version of the code: github:tweag/nickel#packages.x86_64-linux.default github:tweag/nickel/50f47728bf8912a9382214fed2b58b86e4791342#packages.x86_64-linux.default /nix/store/jvd3gawfxwhwddly5bfch4k4rbq90wcw-nickel-lang-0.3.1

**Additional context**
It works on playground https://nickel-lang.org/playground/

**Comment by vkleen** [comment]
We pretty recently changed the multiline string syntax to not require the closing `m`. So, `m%"hello world"%` should work fine on master.

**Comment by pleshevskiy** [comment]
Thank you! It works. Then I'll install the latest release
