### ISSUE TITLE
No LSP completion when an identifier is prefixed by a delimiting character 

### ISSUE THREAD

**Issue by ebresafegaga** [tweag/nickel#1040]
**Describe the bug**
Say we have the following program: 
```
...(string[.]
```
Or something like this: 
```
...{array[.]
```
We don't get any LSP completion.

**Expected behavior**
The LSP just give completion as usual.

**Additional context**
This is happening because the LSP server is adding the delimiting character (`(` and `{`) as part of the identifier

**Comment by yannham** [comment]
Oh, is what was happening during the Nixel session?

**Comment by ebresafegaga** [comment]
Yes
