### ISSUE TITLE
Record contracts containing values are not idempotent

### ISSUE THREAD

**Issue by vkleen** [tweag/nickel#1056]
The following contract in `repro.ncl` exhibits strange behaviour:
```nickel
{
  foo
    | {
      bar | optional,
      baz | optional,
      bat | optional,
    }
    | optional
    = { baz = 1 },
}
```
namely:
```
nickel> let Contract = import "./repro.ncl"
nickel> { foo.bar = 1 } | Contract
{ foo = { baz = 1, bar = 1 } }

nickel> { foo.bar = 1 } | Contract | Contract
error: missing definition for `bat`

nickel> record.fields ({ foo.bar = 1 } | Contract).foo
[ "bar", "baz" ]
nickel> record.fields ({ foo.bar = 1 } | Contract | Contract).foo
[ "bar", "bat", "baz" ]
```

This only happens when the record contract contains a value which needs to be merged with the record it is applied to. For instance, `{} | Contract` and `{} | Contract | Contract` both evaluate to `{ foo = { baz = 1 } }`.

**Comment by yannham** [comment]
The first step of RFC005 is coming in #990, which totally changes how optionals work (while they are currently a bit hacky and sensitive to merging). I suspect you build a merge expression of several empty metadata, and the interpreter can't determine it's actually empty, so consider it as a normal field (an optional field with an actual definition).

Let's see how this example fares with #990.

**Comment by vkleen** [comment]
With #990 merged, this example is evaluated correctly 🎉
