### ISSUE TITLE
Improve the handling of builtin.trace

### ISSUE THREAD

**Issue by vkleen** [tweag/nickel#1069]
With #1055 we have rudimentary support for tracing the evaluation of a Nickel term. However, the implementation naively prints to `stderr` unconditionally. This works fine in the context of `nickel export` on the command line, but is undesirable in a library binding such as the new `pyckel`. Furthermore, in the WASM REPL the trace builtin is ignored entirely.

This issue is supposed to track improvements to our implementation of `builtin.trace` and should be a good place to discuss approaches for handling it. One first suggestion from @yannham was to add an "output stream" feature to the Nickel virtual machine. This output stream could then be handed off to the caller in the case of `pyckel` or be handled by the WASM REPL for the web.

- [ ] Stop printing to `stderr` in `pyckel`
- [ ] Enable `builtin.trace` in the WASM REPL

**Comment by yannham** [comment]
@vkleen do you think this is properly closed by #1338, or is there remaining tasks to achieve?

**Comment by vkleen** [comment]
I think #1338 closes this. We might wish for a more structured approach to this "output stream" idea than just another argument for the evaluator, but that's probably a bridge to be crossed once we get to it.
