### ISSUE TITLE
nickel doc should support displaying on stdout

### ISSUE THREAD

**Issue by rapenne-s** [tweag/nickel#1073]
**Is your feature request related to a problem? Please describe.**

`nickel doc` has support for `-o` flag to give the output file, it would be useful to have the standard `-o -` destination to display the content on stdout.

**Describe the solution you'd like**

`nickel -f file.ncl doc -o -` would display documentation of `file.ncl` on stdout

**Comment by yannham** [comment]
Or should we just print on stdout by default? Might actually be simpler than deciding a default output for the user. We could probably get rid of the `dir` crate or whatever we use to find the home directory. I'm not sure what the saner default here.

**Comment by rapenne-s** [comment]
I don't know the use case for `nickel doc`, but going stdout by default would be a saner default IMO.

Maybe a flag to create a file in the current directory reusing the name of the file in parameter would be great.

**Comment by yannham** [comment]
It's used to generate documentation, like `cargo doc` or whatever is you preferred programming language. It seems like what you want is to generate a file (and, probably later, several files). Well for now we can keep like it is and implement your suggestion as a first step, and revisit the CLI interface in general for 1.0.

**Comment by yannham** [comment]
`nickel doc` has had `--stdout` as an argument for some time now, So I think this can be closed.
