### ISSUE TITLE
[LSP] Improve printing of large record contracts during completion

### ISSUE THREAD

**Issue by ebresafegaga** [tweag/nickel#1094]
Currently, if we have a large record contract associated with an identifier, the LSP output in the editor displays a truncated contract. This can be confusing to a lot of users. The LSP should display just enough information that will be useful to the user.

**Comment by yannham** [comment]
Update: I think it might be linked to #1349. A solution to #1349 could provide a pretty printer configuration where we print record fields and the attached type and contracts, but ignore e.g. documentation (that is printed in the window below anyway on hover) and values (or maybe values if they're not a record, or any heuristics to provide the most relevant information).

**Comment by yannham** [comment]
I believe this is fixed by https://github.com/tweag/nickel/pull/2073.
