### ISSUE TITLE
[LSP] Contracts represented by import terms are not linearized.

### ISSUE THREAD

**Issue by ebresafegaga** [tweag/nickel#1103]
**Describe the bug**
If we have the Nickel program below in our editor, we do not get context completion from `import "a.ncl"`, we cannot navigate to the file in `import "a.ncl"`, and we do not get any hover information from it.
```
{   

} | import "a.ncl"
```

**Expected behavior**
We should treat it as if the contract was written inline, and get all the nice LSP features here.

**Additional context**
The `import "a.ncl"` expression is not linearized, so the LSP does not have knowledge of it. It is not linearized because the parser doesn't attach a position to it in the resulting AST, and terms without a position cannot be linearized, as it will be impossible to interact with it in the editor. 

This is not just a problem special to import terms used in a contract annotation; in fact, most expressions used in a contract annotation are not assigned positions in the resulting AST.

**Comment by jneem** [comment]
Imports are now transparent to most LSP operations.
