### ISSUE TITLE
Mixing Dictionary and Record contracts causes loss of metadata in certain orders

### ISSUE THREAD

**Issue by silverraven691** [tweag/nickel#1111]
**Describe the bug**
I have a record where each field has a common set of defaults and restrictions, and maybe some subfields specific to the field, I therefore tried to model it using a Dictionary contract, to apply all the common contracts and defaults, and then refined using a Record contract. In my understanding of the language, this should be valid and work as I expect, however in practice, the metadata of the Record contract is lost if the Dictionary contract was applied first.

**To Reproduce**
```nickel
{
  Contract = {
    services 
      # The Dictionary contract
      | { _ : ServiceContract }
      # The Record contract
      | {
        httpd.path = "./httpd",
      }
      #
      | default = {},
  },

  ServiceContract = {
    enable : Bool | default = false,
    path : Str,
    .. # It's extensible
  },

  Test = {} | Contract,
}.Test
```
Results in `{ services = { httpd = { path = "./httpd" } } }`

If we apply the Record contract before the Dictionary contract, we get `{ services = { httpd = { path = "./httpd", enable = false } } }`

**Expected behavior**
I would expect the order to not matter.

**Environment**
 - OS name + version: Linux Ubuntu 22.04
 - Version of the code: v0.3.1

**Comment by matthew-healy** [comment]
I'm not sure I can comment on whether or not this is ultimately desirable behaviour, but I can see where things are getting confused. Perhaps it's helpful if I shed some light on what exactly is happening here. 

Essentially, contract application de-sugars to a record merge, and record merging isn't transitive in general. (I.e. it's not true that `(A & B) & C == A & (B & C)` for all records `A`, `B`, and `C`).

In particular, in the case where the "record contract" is applied first, we have:

```
    services | { httpd.path = "./httpd" }
->  services & { httpd.path = "./httpd" }
->  {} & { httpd.path = "./httpd" }       # (since services is declared to be {})
->  { httpd.path = "./httpd" }
```

Now applying the dictionary contract to that, we get:

```
    { httpd.path = "./httpd" } | { _ : ServiceContract }
->  { httpd = { path = "./httpd" } & ServiceContract }
->  { httpd = { path = "./httpd" } & { enable: Bool | default = false, path : Str } }
->  { httpd = { path = "./httpd", enable = false } } 
```

However, if you apply the dictionary contract first, you're applying it to an empty record, which will pass the check by default. Once the contract has been applied & conformance checked, we're just left with the empty record again, and so applying the record contract on top of that just merges the `httpd` value in to the empty record like we did above.

**Comment by silverraven691** [comment]
Ahhh, that does absolutely makes sense thank you. Probably not a bug indeed
