### ISSUE TITLE
Nickel query doesn't print types

### ISSUE THREAD

**Issue by vkleen** [tweag/nickel#1116]
Type annotations are printed as variable numbers in `nickel query`:
```
❯ nickel query uppercase <<<'string'
• type: %120
...
```
They should instead be pretty printed as Nickel types.

**Comment by yannham** [comment]
#1086 changes how metadata are printed (and how type annotations are handled and transformed). There it doesn't show any metadata (as "expected"). Does this issue still stand then (of course we'll wait for #1086 to be merged before closing)?

**Comment by vkleen** [comment]
Yes, the `nickel query uppercase <<<'string'` example works with #1086 👍

**Comment by yannham** [comment]
Ok. Let's close when it gets merged.
