### ISSUE TITLE
 Standard library documentation

### ISSUE THREAD

**Issue by jlesquembre** [tweag/nickel#1122]
**Is your feature request related to a problem? Please describe.**

Nickel has a  standard library, but, as far as I know, it's not documented anywhere. That makes it hard to discover.

**Describe the solution you'd like**

I suggest adding a new section to the [user manual](https://nickel-lang.org/user-manual/introduction). Ideally, we could generate it from https://github.com/tweag/nickel/tree/master/stdlib

**Comment by yannham** [comment]
In fact, the flake already has a `stdlibDoc` output that spits out markdown. It "just" has to be integrated to the website. Or are you talking about having it locally?

**Comment by jlesquembre** [comment]
I didn't notice the `stdlibDoc` in the flake, nice! In that case, the hard part is already done, we only need to ingrate it in the website :)

**Comment by yannham** [comment]
The stdlib doc is now on the unstable deployment branch of the website: https://64491789e8a020730093ff4a--nickel-lang.netlify.app/
