### ISSUE TITLE
Namespacing stdlib modules

### ISSUE THREAD

**Issue by yannham** [tweag/nickel#1131]
**Is your feature request related to a problem? Please describe.**

Since the beginning of Nickel, the stdlib has grown: in particular, quite a few modules were added, like `function`, `record`, `array` or `contract`. They are currently available directly in the environment of each program at the start. This has a number of disadvantages:

1. It's not discoverable. There's no root module/record/value on which we can ask Nickel (through `nickel query` for example) what are the current stdlib modules. We get completion when we start to type them within an LSP-enabled editor, but we need to know - at least partially - what we are looking for first.
2. It's clashing with local names. For example, `array`, `record` and `contract` aren't **un**common to use when writing generic library functions. We already had to use `array_` and `record'` instead. Unwilling shadowing a stdlib module by a local variable happens silently and can be sneaky.

**Describe the solution you'd like**
One solution is to put the whole stdlib in a specific namespace. In practice, it just means putting the modules inside a top-level `std` or `stdlib` record. `array` would become `std.array`, for example. `nickel query <<< 'std'` or typing `std` in a code editor with the Nickel LSP would provide the list of available modules.

**Describe alternatives you've considered**

- Do nothing, putting up with the inconveniences listed above
- Have a proper notion of namespacing, that doesn't rely on records. Modules, for example. However, this solution is complex and hasn't obvious advantages over using a simple record, as proposed in this issue.

**Comment by matthew-healy** [comment]
Really like this idea. My proposal for a name would be `nickel`, though I think `std` also works fine.

**Comment by vkleen** [comment]
That sounds like a very sensible idea. Personally, I like `std` for a name.

**Comment by aspiwack** [comment]
This is probably a good idea. And `std` is probably the better name here as it is very short, since it's going to be written a lot.

But let's be aware that we will see a lot of `std.array.map` and such, which are fairly long function names. At some point we will probably want to figure out mitigations for this.

**Comment by vkleen** [comment]
The obvious mitigation here is to use let bindings:
```
let { map, fold_left, .. } = std.array in
...
```
