### ISSUE TITLE
Improve documentation about label

### ISSUE THREAD

**Issue by rapenne-s** [tweag/nickel#1134]
**Is your feature request related to a problem? Please describe.**

I understand that `label` is very useful for error reporting in user defined contracts, I think they should have a dedicated section about them in the user manual https://nickel-lang.org/user-manual/contracts#by-hand

I might not have read the user manual carefuly enough the first time, I thought `label` was just a component of the example code, by dedicating it a "section" it may be clearer that it's actually a builtin field one can use.

Partially related to https://github.com/tweag/nickel/issues/1052

**Comment by yannham** [comment]
I think this has been fixed: the current documentation has a dedicated section on the `label` parameter after having been heavily revamped following the validator and new custom contract system in 1.8: https://nickel-lang.org/user-manual/contracts/#label
