### ISSUE TITLE
The Syntax Bikeshedding Dojo, round 11: builtin types and modules

### ISSUE THREAD

**Issue by yannham** [tweag/nickel#1147]
The next coming version is `1.0`. After that, backward incompatible changes (in particular, with respect to syntax) will become much more costly, if possible at all without a very good reason. In that spirit, let's try to get rid of possible legacy inconsistencies in the current syntax and builtin naming scheme. This issue is concerned with the builtin types (`Num`, `Str`, etc.) and their corresponding stdlib modules.

## Naming isn't consistent

Currently, the naming scheme of builtin types and the corresponding stdlib modules isn't always consistent:

- The builtin type for strings is `Str` but the stdlib module is `string`
- `Str` and `Num` are 3-letters shortening, but `Array` isn't, for example. `Bool` is 4-letters.

While it's not a huge deal, IMHO, it's the kind of small cuts and historical inconsistencies which add up over time. We have an opportunity right now to fix some of them, although it means making a backward incompatible change. The shortened naming scheme is also reminiscent of languages like Rust and C (Nickel being written in Rust, is that a possible explanation of  `Str` over `String` :thinking: ), while we opted for a rather explicit/long naming scheme elsewhere in Nickel. I tend to think the naming scheme of builtins and stdlib do impact, consciously or not, the style people adopt when writing Nickel.

### Long names

One option is to use full names for both types and stdlib modules. We tend prefer explicit names, even if slightly longer, elsewhere in the stdlib. `String` and `Number` are 6 letters, which is only one more than `Array`. Boolean being a bit longer, and abbreviated pretty much everywhere as `Bool`, it's probably ok to keep it like that.

- Builtin types: `String`, `Number`, `Array`, `Bool`
- Stdlib modules: `string`, `number`, `array` (there's currently no module corresponding to booleans, but would be `bool`)

### Keep current short names

Another option (still a breaking change, but less impactful than the previous one, in sheer numbers of LoC to fix) is to keep the same name for builtin types, but at least make the stdlib modules match it. Giving:

- Builtin types (unchanged): `Str`, `Num`, `Array`, `Bool`
- Stdlib modules (only string changed): `str`, `num`, `array` (`bool`)

**Comment by aspiwack** [comment]
> Boolean being a bit longer, and abbreviated pretty much everywhere as `Bool`, it's probably ok to keep it like that.

Plus, everybody says “a bool” anyway. You will sometimes say “a num” and almost never say “a str”. So there's that…

I'll cast a weak vote for the long-names-except-bool proposal.

**Comment by vkleen** [comment]
Consistency here is probably more important than typing fewer characters, especially with modern autocompletion tools and the like. I'll vote for long-names-except-bool as well.

**Comment by matthew-healy** [comment]
Another +1 for "long names in general but let's keep `Bool` short for historical reasons"

**Comment by asymmetric** [comment]
As an outsider, I vote for the long names, but I'd also consider being consistent and changing `Bool` to `Boolean`, for these two reasons:

- consistency :)
- as was said, editors will auto-complete long keywords
- people will continue pronouncing it however they've been pronouncing it (me personally, I've always said boolean)

**Comment by yannham** [comment]
I didn't mention `Dyn`, by the way. Should we keep it like it is? Write it `Dynamic`? Or use a more explicit name? I wonder how much `Dynamic` is meaningful for people that don't know much about gradual typing. `Any` would be more common, but doesn't really fit Nickel's type system (`Dyn` is not something that can be used as any type, as e.g. in TypeScript, Mypy, or Luau). It would rather be the `Unknown` type.

**Comment by matthew-healy** [comment]
Definitely agreed that `Any` doesn't feel suitable without a `forall a. a <: Any` typing rule.

I quite like `Unknown`! If I was being picky I'd maybe say that it could look confusing in error messages. E.g. `expected Number but got Unknown` could be misunderstood to mean "we couldn't work out the type" rather than "this is not statically typed". That being said, TypeScript uses `unknown` for a very similar purpose (see [here](https://www.typescriptlang.org/docs/handbook/basic-types.html#unknown)).

As for `Dynamic`, I think that even if people aren't familiar with gradual typing, it's the natural counterpoint to "statically typed".

I think my hierarchy of preferences here would be: `Unknown > Dynamic > Dyn > Any`.

**Comment by yannham** [comment]
> Definitely agreed that Any doesn't feel suitable without a forall a. a <: Any typing rule.

FYI, it depends how you interpret this rule, but this rule can be made true in some sense (that's what RFC004 aims at doing) in a reasonable extension of the current type system.

The issue IMHO is that you don't have the converse, that is, you can't use an `Any` when something more precise is expected, which is usually something you can do in the traditional gradual type systems like TypeScript, Mypy or Luau. `Any` is usually the gradual type, while in Nickel, `Dyn` is actually just a top type (or equivalently an existential type `exists a. a`,  or yet a union type of all the existing types, if such a thing is definable), which is different.

**Comment by aspiwack** [comment]
It's debatable whether the difference is `Any` vs `Dyn`, or if it's a philosophical difference in type systems: we reject programs when we don't know that they are well-typed, they reject programs when they know that they're ill-typed.

**Comment by matthew-healy** [comment]
> you can't use an Any when something more precise is expected

Maybe I'm misunderstanding, but you could do it with a contract annotation, right? e.g.

```
let a : Any = 1 in
let b : Num = 1 in
let add : Num -> Num -> Num = fun a b => a + b in
add (a | Num) b
```

That feels roughly equivalent to how it'd work in, e.g., Rust/Swift/Scala, where the `Any` type needs to be coerced/cast before it can be used. (Though admittedly none of those type systems are gradual, modulo some ObjC/Java interop in the latter two.)
