### ISSUE TITLE
Nickel diff

### ISSUE THREAD

**Issue by stephenmw** [tweag/nickel#1215]
Are there plans to include a standard way to diff a Nickel configuration?

A common problem I have in various systems with configuration through code is refactoring correctly. When I refactor, I need to have a way to ensure my refactor results in zero configuration changes. If it does result in configuration changes, I need to know what they are so that I can either fix them or ignore them. For example, in most refactors I add new configuration options but I expect old ones to remain the same (even if the code that builds them changed).

**Comment by yannham** [comment]
As of today, I imagine the simplest is to evaluate your configuration away to, say, JSON an diff on the result (with e.g. [jd](https://github.com/josephburnett/jd#command-line-usage)), a small script like:

Having a diffing tool is not out of the question, but right now there's no active plan for that. Do you have a specific use-case in mind that wouldn't covered by diffing on the result? I can see a usage for parametric configurations (or "modules"), where all values aren't bound yet. But on the other hand, I tend to think that what's count in practice is mostly the final configuration, which is the closest to what is actually passed to the target tool. So I'm curious about your specific motivation :slightly_smiling_face:

**Comment by yannham** [comment]
Without further information on the motivation or the scope of such a tool, I'm closing for now. Feel free to re-open if you have further information.
