### ISSUE TITLE
No auto-completion in tf-ncl

### ISSUE THREAD

**Issue by yannham** [tweag/nickel#1221]
**Describe the bug**
When initializing a flake from the template of https://github.com/tweag/tf-ncl (say commit dcdbc5a09778336cfdfa558642a56fe668e192fb), and using some provider (say "google"), we don't get any completion nor documentation in the LSP when hacking on the example. Given that the contract is defined as a succession of records and dictionary contracts, I don't see an obvious reason why we wouldn't have completion (another thing to consider is that the generated contract is 300K lines and 16MB, so the LSP might choke on it - to be investigated)

**To Reproduce**

1. Initialize a flake from tf-ncl on commit `dcdbc5a09778336cfdfa558642a56fe668e192fb`: `nix flake init --template github:tweag/tf-ncl/dcdbc5a09778336cfdfa558642a56fe668e192fb`
2. Replace the `null` provider by `google` L.26
3. Start the development shell (`nix develop`)
4. Hack on `hello-tf.ncl`, and try to add new fields to the `config` record, waiting for completion to help. Nothing happens.

**Expected behavior**

That context auto-completion works.

**Additional context**

The issue seems to be that `Tf.Config` define a schema like this

```nickel
    Config = {
        config | Schema,
        renderable_config = TfNcl.mkConfig config,
        ..
    },
  Schema = {
   data | ...
  }
```

Because of the indirection, the LSP doesn't seem to pick the information that `config` have fields defined by `Schema`.

**Comment by ebresafegaga** [comment]
On my end, it seems like the import doesn't resolve correctly:

![image](https://user-images.githubusercontent.com/32538936/230119144-29a24db6-b9e9-41e0-ac47-d0d49a649c3e.png)

**Comment by yannham** [comment]
Ah yes, you need to do `init` I think. Something like `terraform hello-tf.ncl init` ?
