### ISSUE TITLE
Not_exported fields get evaluated during export anyways

### ISSUE THREAD

**Issue by vkleen** [tweag/nickel#1230]
# Situation
A `nickel export` evaluates a program fully before continuing on the `export` codepath. Consequently, when exporting a toplevel record, all record fields will be evaluated, even if they will never appear in the result. On the one hand, this can be a performance problem. On the other hand, it can also be quite puzzling when building a configuration piecemeal using merging. Consider:
```nickel
let Module = {
  configs
    | not_exported
    | Array {..},
  module
    | not_exported
    | {
      config | {..},
      output | {..},
    },
  output = configs |> array.map (fun config' => (module & { config = config' }).output),
} in
{
  configs = [
    { os = "a" },
    { os = "b" },
  ],
  module = {
    config,
    output = { on = config.os },
  },
} & Module
```
Before starting the export, Nickel will evaluate this configuration fully and rightfully complain that the `config` field in `module` doesn't have a definition. But a user may expect (and we *did* expect during a recent Nickel hour) that with `nickel export` the `module` field never gets evaluated standalone.

# Possible approaches

- We could not do anything, except documenting that behaviour. The current semantics are reasonably clear.
- We could introduce a variant of `UnaryOp::Force` which doesn't descend into fields marked as `not_exported`.

**Comment by yannham** [comment]
I think I'm partial to the second option. It can just be a parameter to `UnaryOp::Force` (parameters that are just `Copy`able enum are fine, IMHO), so that we don't have to add a new primop or the like.
