### ISSUE TITLE
`std.fail_with` fails (but not in the expected way)

### ISSUE THREAD

**Issue by yannham** [tweag/nickel#1248]
**Describe the bug**
`std.fail_with` fails with an unexpected identifier over the use of `FailWith`. Well, it's expected to fail, but not in this way.

**To Reproduce**

```text
nickel> std.fail_with "foo"
error: unbound identifier `FailWith`
     ┌─ <stdlib/std.ncl>:2555:26
     │
2555 │     = fun msg => (null | FailWith msg),
     │                          ^^^^^^^^ this identifier is unbound
```

**Expected behavior**
`std.fail_with msg` should raise a contract error which includes the given message `msg`.

**Additional context**
The identifier isn't actually unbound (at least syntactically). I suspect that since we put everything under the std namespace, something was overlooked with respect to transformation, and the top-level record `std` doesn't get transformed, which breaks recursive records. Indeed, `FailWith` seems to be one of the rare occurrence of recursive cross-references at the top-level `std` module itself.

**Comment by vkleen** [comment]
Didn't we want to avoid recursive references in the `stdlib` entirely, for typechecking reasons? Then the best way to fix this would probably to just use `std.FailWith` in `std.fail_with`.
