### ISSUE TITLE
Nickel happily accepts a record type literal with several declarations for the same row

### ISSUE THREAD

**Issue by yannham** [tweag/nickel#1284]
**Describe the bug**
Nickel accepts ill-formed record types, where the same field is defined several time, while it should reject them.

**To Reproduce**

```
nickel> ({foo.bar.baz = "a"} : {foo : String, foo : Number})
error: type error: missing row `foo`
  ┌─ repl-input-2:1:2
  │
1 │ ({foo.bar.baz = "a"} : {foo : String, foo : Number})
  │  ^^^^^^^^^^^^^^^^^^^ this expression
  │
  = The type of the expression was expected to be { foo: String, foo: Number }, which contains the field `foo`
  = The type of the expression was inferred to be { foo: String }, which does not contain the field `foo`
```

**Expected behavior**
I expect the previous example to either fail with a specific parsing error, or to at least not consider this as a record type, but as a general record literal.

**Additional context**
This probably comes from the way `UniRecord` are converted to record types. Unirecords are just a list of declaration, with potential duplicates, but the check for record types just look for field with type annotation and without definitions. Is suspect it doesn't check for duplicate fields. This is wild guessing, and I haven't actually investigated the issue.

**Comment by matthew-healy** [comment]
FYI, this might be related to both of #1098 and #1117.
