### ISSUE TITLE
"Expected" & "found" types are inconsistent in type mismatch errors

### ISSUE THREAD

**Issue by matthew-healy** [tweag/nickel#1315]
**Describe the bug**

Type mismatch error message are presented to users with the note that some type was "expected" but a different type was "found". However, these don't always match the intuitive understanding of what might have gone wrong. 

**To Reproduce**

One such program with this issue is:

```ncl
[(1 : String), true, "b"] : Array Dyn
```

which results in the error:

```
error: incompatible types
  ┌─ repl-input-1:1:3
  │
1 │ [(1 : String), true, "b"] : Array Dyn
  │   ^ this expression
  │
  = Expected an expression of type `String`
  = Found an expression of type `Dyn`
  = These types are not compatible
```

It seems pretty clear that, in this case, the _expected_ type of the array's elements is `Dyn`, and the _found_ type is `String`.

**Additional context**

Part of the issue here is that when performing unification against chains of unification variables, it's not always clear what the "expected" or "actual" types were in the erroneous code. @vkleen suggested this may end up significantly easier to fix once we've moved to a proper bidirectional typechecking algorithm.

**Comment by jneem** [comment]
I don't understand what's wrong with this error message: I get the same thing from
```
1: String
error: incompatible types
  ┌─ repl-input-0:1:1
  │
1 │ 1: String
  │ ^ this expression
  │
  = Expected an expression of type `String`
  = Found an expression of type `Number`
  = These types are not compatible
```
and this looks like the right error to me...

**Comment by matthew-healy** [comment]
@jneem Yeah, as your edit says, the difference between the case in the issue and yours is the "found" type. If the error in the issue said that `Number` had been found then it'd be fine.

The reason I thought this was related to flipping the expected & found types is that I assumed the `Dyn` was coming from the `Array Dyn` annotation. It still might be, but I definitely agree that just raising that `1` isn't a `Number` is probably the right error here.

**Comment by yannham** [comment]
I think this is a bug. Although unification is undirected, we still have a form of bidirectional discipline, and the order of arguments to `unify` actually matter (not semantically - it doesn't influence the fact that something typecheck or not - but precisely for error messages). I haven't looked into that but I agree that in this case "expected" and "actual" should be swapped, and I can't see an obvious reason why it isn't working the way it should.

**Comment by yannham** [comment]
This is indeed solved by the former bidirectional typechecking completion in current Nickel:

```
nickel> [(1 : String), true, "b"] : Array Dyn
error: incompatible types
  ┌─ <repl-input-8>:1:3
  │
1 │ [(1 : String), true, "b"] : Array Dyn
  │   ^ this expression
  │
  = Expected an expression of type `String`
  = Found an expression of type `Number`
  = These types are not compatible
```

In particular some heavy refactoring of the error messages was done, which fixed a number of issues with the inconsistent "found/expected" kind of issues.
