### ISSUE TITLE
Website: docs out of date

### ISSUE THREAD

**Issue by Jasha10** [tweag/nickel#1329]
As of this writing, the latest release of nickel is v1.0.0.

The nickel-lang.org website's [user-manual/introduction](https://nickel-lang.org/user-manual/introduction) page says "Nickel is currently released in version 0.3.1."

It would be nice to have an up-to-date version of the docs so I can learn about v1.0.

**Comment by vkleen** [comment]
The docs are up-to-date except for the version number; feel free to peruse :)

**Comment by vkleen** [comment]
This is fixed on the website now.
