### ISSUE TITLE
support scientific notation for numbers

### ISSUE THREAD

**Issue by MMesch** [tweag/nickel#1361]
**Is your feature request related to a problem? Please describe.**

I am always frustrated when I can't write numbers as `1e12` and have to write `1000000000000` instead. It's easy to make a mistake that way :)

**Describe the solution you'd like**

Support for scientific notation for numbers such as `1e12` would be a good solution, in my opinion.

**Comment by yannham** [comment]
I would add to the mix: should we also support common computer units? For example, I think you can write `12MiB` or `12MB` in CUE, which can come in handy to configure e.g. space allocation.

**Comment by yannham** [comment]
And second suggestion: we should probably support a delimiter, such as `_`, to make numbers like `1000000001` more readable, like `1_000_000_001`.

**Comment by vkleen** [comment]
For scientific notation, `malachite` already supports converting from scientific notation, so we'll only need to change the lexer to allow this.

**Comment by yannham** [comment]
Let's focus on scientific notation then, and open other issues accordingly for the other issues.

**Comment by vkleen** [comment]
With #1456 we have scientific notation in Nickel.
