### ISSUE TITLE
Include syntax highlighting in vscode extension

### ISSUE THREAD

**Issue by simonzkl** [tweag/nickel#1363]
**Is your feature request related to a problem? Please describe.**
The vscode extension right now only does LSP and relies on a third party vscode extension for syntax highlighting. The third party extension is out of date as well and doesn't support keywords introduced in 1.0.

**Describe the solution you'd like**
The syntax highlighting should be implemented in the official vscode extension.

**Describe alternatives you've considered**
I don't feel like having these separate makes sense from a user's perspective. Especially as the official lsp extension relies on the `nickel` language being registered. So the unofficial syntax highlighting extension is actually a hard requirement.

**Comment by yannham** [comment]
I'm not a VSCode user, so I don't know much about extension development, but that would be great if we could just piggy-back on tree-sitter, as we maintain a fairly up-to-date grammar already. It's hard to keep the number down (Vim, the Nickel parser, Prism.js for highlighting on the website, etc.), but the less grammars we have to maintain, the better :slightly_smiling_face:

**Comment by szlend** [comment]
There's no vscode tree-sitter support yet, but they're discussing it. Until then I quickly hacked together a more complete and up to date vscode package: 

https://marketplace.visualstudio.com/items?itemName=szlend.unofficial-vscode-nickel

**Comment by yannham** [comment]
Thanks @szlend, we're going to take a look, maybe re-use what you did as a base. I dream that one day we will only write one grammar specification, and derive a parser, various highlighters and plugins for editors, whatever is needed for a formatter, etc. but that day hasn't come yet :disappointed:

**Comment by szlend** [comment]
Done in PR https://github.com/tweag/nickel/pull/1405

**Comment by yannham** [comment]
Syntax highlighting has been added and the extension is now available on the VSCode Market Place: https://marketplace.visualstudio.com/items?itemName=Tweag.vscode-nickel
