### ISSUE TITLE
Publish vscode extension to the extension marketplace

### ISSUE THREAD

**Issue by simonzkl** [tweag/nickel#1364]
**Is your feature request related to a problem? Please describe.**
Setting up the vscode extension for lsp is too complicated. Expecting people to install Nix and build it manually limits adoption.

**Describe the solution you'd like**
Now that 1.0 has been released, it should just be available in the official extension market place.

I can help test it out a bit and fix a few remaining bugs (e.g. currently it watches for `**/.ncl`, which is clearly wrong). We might also wanna resolve https://github.com/tweag/nickel/issues/1363 first. But other than that, are there any objections to doing this after these are resolved?

**Comment by yannham** [comment]
Hi @simonzkl , sorry, this issue has somehow not been noticed (I might have confused it with #1363). No objection at all here, would gladly review and accept PRs to integrate what you did to the extension maintained in this repository, including syntax and publishing the extension to the market place.

**Comment by szlend** [comment]
Actually I just went and ported mine here: https://github.com/tweag/nickel/pull/1405

**Comment by yannham** [comment]
Now available at https://marketplace.visualstudio.com/items?itemName=Tweag.vscode-nickel

**Comment by szlend** [comment]
Thank you for helping get this out! You guys went above and beyond with this given nobody in the team actually uses vscode. I think it's gonna pay off in adoption!
