### ISSUE TITLE
Typechecker hangs on certain polymorphic terms

### ISSUE THREAD

**Issue by vkleen** [tweag/nickel#1389]
The Nickel type checker loops apparently infinitely when checking
```
(std.array.fold_right (fun result acc => if result.success then acc else result)) :_
```

The required ingredients seem to be:
- a polymorphic higher order function, minimally of type `forall a b. (a -> b -> b) -> a -> Dyn` I think
- record access as in `result.success`
- an if-then-else expression determining the return type

**Comment by yannham** [comment]
I'm not sure it's really related, but just in case: #277.
