### ISSUE TITLE
"Nearest" rounding for large numbers is surprising

### ISSUE THREAD

**Issue by vkleen** [tweag/nickel#1457]
Something that has only really become a concern with the new support for scientific notation:
```
nickel> std.serialize 'Json 1.7e400
"1.7976931348623157e308"
```
This should really be a serialization error, because the number doesn't fit into the specified 64bit float. Just clamping it to the maximum representable number may be technically valid ("the closest float64 to the input number") but it's very surprising.

This is a result of us using `malachite`'s `f64:rounding_from(n, RoundingMode::Nearest)` for serializing numbers that are not representable as 64-bit integers. `RoundingMode::Nearest` is explicitly specified to always return the nearest finite floating point number, which is of course `f64::MAX` for very large inputs.

**Comment by aspiwack** [comment]
Question: why are we serialising to a 64-bit floating point number?

**Comment by vkleen** [comment]
I think because most JSON implementations assume numbers are 64-bit floats, although the standard allows any decimal number in scientific notation.

**Comment by yannham** [comment]
Another technical reason is that the `serde` model, that we rely upon to serialize to and from various format, only support serializing from and to some set of number representations, such as `i16`,`i32`,`i64`,`i128`,`u16` and so on. The only two non integer types supported are `f32` and `f64`. It's just a technical and not an absolute limitation, but that would mean departing from serde to at least (de)serialize JSON. The TOML spec for example says that [floating point numbers are f64](https://toml.io/en/v1.0.0#float).

I suppose this is for the same reason Viktor mentioned: it's probably illusory to expect various (de)serializer from other apps written in various programming languages to handle arbitrary large numbers, although you could theoretically write them in full. I think one the best we can guarantee is that within Nickel, all calculations you do are exact (as long as you don't use some operations such as non-integer exponentiation), but it sounds difficult to avoid any approximation/projections happening at the (de)serialization border.
