### ISSUE TITLE
Relative imports to the parent dir behave weirdly

### ISSUE THREAD

**Issue by thufschmitt** [tweag/nickel#1482]
**Describe the bug**

Given a directory tree like

```
.
├── bar.ncl
└── foo
    └── foo.ncl
```

where `foo.ncl` contains `import "../bar.ncl"`, running `nickel export -f foo/foo.ncl` from the toplevel works, but `cd foo && nickel export -f foo.ncl` fails with

```
error: import of ../bar.ncl failed: No such file or directory (os error 2)
  ┌─ foo.ncl:1:1
  │
1 │ import "../bar.ncl"
  │ ------------------- imported here
```

**To Reproduce**

Create a file tree like above and try

**Expected behavior**

Either both should fail (if we want to forbid imports going up in the fs hierarchy) or both should succeed

**Environment**
 - OS name + version: NixOS 23.05
 - Version of the code: 1.1.1

**Comment by silverraven691** [comment]
Just FYI, we just hit this bug using v1.1.1, it would have been nice to push a patch release after fixing :)

**Comment by jneem** [comment]
I just went to add "decide on a release policy/schedule" to the agenda for the [next weekly](https://docs.google.com/document/d/1MlJdr-uqhHIY1Fe-Vqi4d9gnwMgKRiLqIvbBFzR1xDY/edit?usp=sharing), but it seems that someone beat me to it...

**Comment by simonzkl** [comment]
@jneem This is a pretty major breaking change so it would make sense to get this hotfix out asap. The longer this is left broken, the more likely it is that someone will start relying on it.

**Comment by jneem** [comment]
There's a release in the works (along with a coming policy on regular releases, and some work to make them easier)
