### ISSUE TITLE
Issue an error when providing no field path to `--query`

### ISSUE THREAD

**Issue by yannham** [tweag/nickel#1487]
**Describe the bug**
The query subcommand takes a program to evaluate, and a field path. It then extracts the metadata - if any - of the corresponding field.

Since RFC005 (#819), querying a configuration without providing a field path doesn't make sense: metadata can only be located at the level of a record field. However, probably for historical reasons, the current CLI accepts it and just always spit "Metadata not found for this value.". This can be confusing, in particular because in the REPL, one provide just one argument which is field path. Thus, `:query std.record.map` in the REPL correctly return the documentation of `map`, but `nickel query <<< std.record.map` doesn't. Indeed, the correct way is `nickel query record.map <<< std` or `nickel query map <<< std.record`.

**To Reproduce**
```console
$ nickel query <<< std.record.map
Requested metadata were not found for this value.
```

**Expected behavior**
The `query` command should make the field path a required argument and error out on such an invocation.

**Comment by vkleen** [comment]
We might want more nuance than this. It makes perfect sense to query a configuration that happens to be a top-level record to discover which fields are available. Still, the current situation is unsatisfactory. How about we issue an error about a missing query path if the value being queried isn't a record?
