### ISSUE TITLE
More eager lsp check

### ISSUE THREAD

**Issue by thufschmitt** [tweag/nickel#1501]
**Is your feature request related to a problem? Please describe.**

The lsp currently checks the syntax and types of its input. For performance reasons (I guess), it doesn't check the contracts. But there's a fair amount of Nickel expressions which would be fast-enough to contract-check and where having an early feedback on contract violations would be immensely useful (esp. since the type system isn't really usable in client code).

**Describe the solution you'd like**

Optionally (not sure how to configure this the best way) have the LSP eagerly check the contracts for its input (well evaluate it).

**Describe alternatives you've considered**

Run `nickel export` automatically on save in my editor. But it's not as nice and transparent (esp with #1500 )

**Comment by yannham** [comment]
There's different ways to go about this, but note that in general checking a local contract might require values from the outer scope, or even values that aren't known at writing time (such as inputs of the configuration). On way could be to try to evaluate the expression, and just ignore any error that isn't a contract error (such as missing field, or even just classify errors that should be reported immediately versus the ones that could stem from evaluating just a fragment of the program). Another possibility, for simple cases, could be to try to infer a type for the subexpression, and compare that to basic contracts - if it fails to typecheck, we can't say anything, but if it succeeds with a type that is incompatible with the contract, then there is a problem. Both approaches (and there's probably more, such as just running the full program and reporting any error on command) have different trade-offs: the partial evaluation one is simple and generic, and handle custom contracts, but can't handle unkown inputs (i.e won't report obviously wrong things such as `{ foo | Number, bar | String = foo ++ "a"}`). The typing approach can't handle custom contract, and can't handle ill-typed terms (that aren't necessarily wrong, just not accepted by the static typechecker), but better handle incomplete values. Or maybe we can combine both?

**Comment by yannham** [comment]
```[tasklist]
### Tasks
- [ ] Example task
```

**Comment by yannham** [comment]
I believe this is closed by the same PR as #1586, giving stuff like this in practice:

![image](https://github.com/tweag/nickel/assets/6530104/49a6a04f-a12c-483e-ae68-e5091fb9237b)

Feel free to re-open, or open new issues for more specific aspects of in-code contract evaluation.
