### ISSUE TITLE
Support completion while in the middle of a record

### ISSUE THREAD

**Issue by thufschmitt** [tweag/nickel#1514]
**Is your feature request related to a problem? Please describe.**

The LSP parser is (fortunately) able to work with _some_ kind of incomplete ASTs. In particular, it's able to handle just fine something like `{ x = foo.<CURSOR> }` (although this expression isn't syntactically correct _yet_).
However, it breaks down on
```nickel
{
  x = foo.<CURSOR>
  y = 1,
}
```

This is quite annoying, because a situation like that is very likely to happen when updating some configuration in Nickel.

**Describe the solution you'd like**

Handle the above case properly.

**Additional context**

The parser handles it just fine if we add a comma (`{ x = foo.<CURSOR> , y = 1 }`). Maybe there could be a heuristic saying that if there's something of the form `<IDENT> =` after the cursor, we can consider it as a new field? Or if that's too brittle, we could just ignore everything after the cursor until the next closing brace (which could be very wrong, but probably enough to get completion to work)

**Comment by jneem** [comment]
I'm not sure exactly which commit fixed it, but on current master if I have
```nickel
let foo = { blahblah = 1 } in
{
  x = foo.
  y = 1,
}
```
with my cursor after the `foo.`, it offers `blahblah` as a completion.

There is still a limitation with completions coming from the following part of the incomplete record: if you have
```nickel
{
  x = foo.
  foo = { blahblah = 1 },
}
```
then it doesn't offer `blahblah` as a completion (unless there's a comma after the `foo.`).

**Comment by yannham** [comment]
I confirm that the original example is fixed on master. @thufschmitt, do you feel like this solves your use-case? Or does the second issue mentioned by @jneem is a current, actual limitation for you as well? If the former, I suggest we close this issue and open another one for the nested case, if needed.

**Comment by thufschmitt** [comment]
I'll open another one for the nested case as it'd be a useful improvement, but having it solved in the “flat” case, is probably solving the 90% most common cases. Thanks whoever accidentally fixed it!
