### ISSUE TITLE
Weird `nickel doc` output on record contracts

### ISSUE THREAD

**Issue by thufschmitt** [tweag/nickel#1519]
**Describe the bug**

When a record field has a contract which is itself a record with contract annotations, `nickel doc` doesn't print it properly and displays something like `let %182 = C in { x | %182…` (with the ellipsis), where the actual contract is `{ x | C, y }`.
This doesn't happen if the contract is instead a type annotation.

**To Reproduce**

```console
$ nickel doc --stdout <<EOF
{
  foo | { x | Dyn, y }
}
EOF
```

**Expected behavior**

The resulting documentation should be something like

```markdown
# `foo`

- `foo | { x | Dyn, y }`
```

**Environment**
 - OS name + version: NixOS 23.05
 - Version of the code: aa4bb20b3e612f7b9797f926df26e53440c3f288

**Additional context**

**Comment by thufschmitt** [comment]
Briefly looking at the code, it seems that the record contract is actually interpreted as a `TypeF::Flat` (a contract defined as an expression) and not as a `TypeF::Dict { flavour = DictTypeFlavour::Contract }` like I suspect it should be. And the pretty-printer then adds the extra `let` to prevent issues with the recursive scoping

**Comment by yannham** [comment]
We're going to look at this, but it's probably related to the fact that `nickel doc` ramped up and do some evaluation. This sounds like now things are transformed and don't look like what they were initially (I'm pretty sure your type is indeed parsed as a `Dict`, it's just transformed away). It might be as simple as relying on `label.orig_type`, which we use for contract error reporting (we have the same issue on contract errors: stuff have been transformated, evaluated and closurized, so we store the original form of the type as the user wrote it).
