### ISSUE TITLE
LSP regression when hovering on the `function` field in `std.xxx.function`

### ISSUE THREAD

**Issue by yannham** [tweag/nickel#1574]
**Describe the bug**

Hovering on an item from the stdlib doesn't always provide the associated metadata (type and documentation), but just shows `Dyn`. This is a regression since 1.1.1, because the latter does show the correct information.

**To Reproduce**

Take the following snippet:

```nickel
let map_cartesian
  : forall a b c. (a -> b -> c) -> Array a -> Array b -> Array c
  = fun f left right =>
    std.array.fold_left
      (
        fun acc_ext left =>
          acc_ext
          @ (
            std.array.fold_left (fun acc_int right => std.array.append (f left right) acc_int) [] right
          )
      )
      []
      left
  in
map_cartesian (++) ["1", "2", "3"] ["a", "b", "c"]
```

And hover on one of the occurrence of `fold_left` in `std.array.fold_left`. The LSP just shows `Dyn`.

**Expected behavior**
I expect the LSP to show the type and the documentation of `std.array.fold_left`, as it does in version 1.1.1.

**Environment**
 - Version of the code: 795e2677fe0bc314984223067b704669723449fb

**Comment by jneem** [comment]
I bisected the bad commit to the bidirectional typechecking one (0f02aa14b742fc3819e9aff62a5b65b245321357). I'll dig a bit deeper, but maybe @yannham has a suggestion on where to look first?

**Comment by jneem** [comment]
Smaller reproducing example:

```
let map: Array Number = std.array.map (fun x => 1) [] in map
```

Hovering over the `std.array.map` shows `Dyn`. Removing the `Array Number` annotation fixes it.

**Comment by yannham** [comment]
> I bisected the bad commit to the bidirectional typechecking one (https://github.com/tweag/nickel/commit/0f02aa14b742fc3819e9aff62a5b65b245321357). I'll dig a bit deeper, but maybe @yannham has a suggestion on where to look first?

Ah, interesting. I would have suspected pure LSP code first, but the typechecker does interact with the linearizer interface, and the bidirectional typechecking PR did restructure quite a bit the flow of the main check function. I'm looking into it, to see if there's a missing `retype_ident` or whatever information the typechecker is providing to the LSP after this commit.

Thanks for investigating this.
