### ISSUE TITLE
Change the manual font to something more readable

### ISSUE THREAD

**Issue by giorgiga** [tweag/nickel#1685]
In the manual at https://nickel-lang.org/user-manual/ commas and dots are not easily distinguishable (well, at least on my system); it would be great if the font was swapped for a clearer one.

Example from https://nickel-lang.org/user-manual/syntax:

![commadot](https://github.com/tweag/nickel/assets/471835/13c24599-fd24-4173-93f0-5b8bf772e43b)

(in case it matters: I'm using latest firefox on an updated tumbleweed w/ kde/wayland)

**Comment by yannham** [comment]
Hi,

Sorry for answering only now. I think the font is defined by default by the Prism library that we use to highlight Nickel code snippets, and is - I believe - rather common for code (DejaVu Sans Mono). Would you have, by any chance, a suggestion for a font with makes the distinction easier?

**Comment by yannham** [comment]
Because there's no answer, and I don't have the same rendering (I see comma clearly differently than dot, see below), I'm going to close for now. Feel free to re-open with suggestions.

![image](https://github.com/tweag/nickel/assets/6530104/0771b1ac-de14-45c5-bc06-95235a9474e4)

**Comment by giorgiga** [comment]
Sorry: I had lost track of this one.

The font that is rendered unclearly is Andale Mono, which is the third alternative (my system came with only the essential fonts and I didn't install many more).

Just removing Andale Mono from the css (`font-family: Consolas,Monaco,Andale Mono,Ubuntu Mono,monospace`) causes the browser to fall back to some other font (the generic "monospace" for me) and solves the issue.

Note that, for all I know, this might be a idiosyncrasy of my browser/os (I run firefox on opensuse tumbleweed) so... just ignore the whole thing if it doesn't add up for you.
