### ISSUE TITLE
Comparison to KCL (a similar constraints-based language)

### ISSUE THREAD

**Issue by bew** [tweag/nickel#1687]
**Is your feature request related to a problem? Please describe.**
I recently been made aware of the [KCL](https://kcl-lang.io/) tool, in a blog post using it as a structured data checker (was showing a nice usecase: checking the json output of terraform plan is not deleting some important resources).

There is a comparison of KCL vs Nickel [in their documentation](https://kcl-lang.io/docs/user_docs/getting-started/intro#vs-nickel), this feels like a simplistic comparison but I'm not sure how..

**Describe the solution you'd like**
I think it would be interesting to have in our comparaison page a comparison of Nickel vs KCL, and how they are different.

**Comment by yannham** [comment]
Related: https://github.com/tweag/nickel/discussions/1582

**Comment by yannham** [comment]
Although it's short, there's now a basic comparison in the RATIONALE document: https://github.com/tweag/nickel/blob/master/RATIONALE.md#kcl-python-like-syntax-with-object-oriented-schemas. I'm closing for now; feel free to ask me to re-open or to open a new issue if you think this is insufficient/too limited.

**Comment by bew** [comment]
Looks great, thanks 👌
