### ISSUE TITLE
Please upgrade to Malachite 0.4.3

### ISSUE THREAD

**Issue by mhogrefe** [tweag/nickel#1704]
Versions of Malachite prior to 0.4.3 have a bug where multiplying certain large `Natural`s or `Integer`s panics. See https://github.com/mhogrefe/malachite/issues/29 for details. Please upgrade your version of Malachite so that this issue doesn't affect Nickel.

I'm the primary developer of Malachite, and it's in my interest for Malachite users to have the smoothest experience possible! Malachite has had some minor API changes in the last few versions, and while I don't expect you to run into problems upgrading, please let me know if you do.

**Comment by mhogrefe** [comment]
Sorry, v0.4.3 had some wrong dependencies. Please use v0.4.4 instead.

**Comment by yannham** [comment]
Hi, thanks for the warning! A PR is up.
