### ISSUE TITLE
Parametrized list type

### ISSUE THREAD

**Issue by yannham** [tweag/nickel#171]
**Is your feature request related to a problem? Please describe.**
Currently, we just have a `List` type for heterogeneous lists. A parametrized list type `List t` is more expressive, as it make the old `List` type representable as `List Dyn`, but it also makes it possible to represent lists which hold items of one fixed type, which is a common thing to use.

**Describe the solution you'd like**
Have a parametrized list type `List t`, where `t` is a type.

**Comment by Profpatsch** [comment]
Semi-related, there is also the need for a `Map Text a` datatype; and the (row) type system should be able to convert
* A record where all fields are of type `a` to a `Map Text a` with a dynamic lookup
* A `Map Text a` back to a “record where all fields have `a`s and fields x, y and z exist (check done at runtime presumably).

The second point a giant shortcoming in dhall right now (it cannot do it statically at type checking time).

**Comment by yannham** [comment]
@Profpatsch, a `Map Text a` is already representable in Nickel through the `{_ : a}` row type, which means a record with all fields of type `a`. You have dynamic access, dynamic removal of field and dynamic extension on every record. I think we don't need a separate type, or am I missing something ?

**Comment by Profpatsch** [comment]
Probably not, I’m not too familiar with what row types can do. I’m looking
forward to playing around with it!
