### ISSUE TITLE
Regression 1.2.3 -> 1.3.0: goto definition on an import expression doesn't work anymore

### ISSUE THREAD

**Issue by yannham** [tweag/nickel#1754]
**Describe the bug**

In the LSP, requesting a _go to definition_ when the cursor is on an import statement used to jump to the corresponding file. I checked and this behavior is still there for 1.2.2.

However, since 1.3.0, the 

**To Reproduce**

```nickel
# file a.ncl
null

# file b.ncl
{
  a = import "./a.ncl",
}
```

Now go to definition when the cursors is somewhere within `import "./a.ncl"` will just show "definition not found".

**Expected behavior**

I expect that requesting the definition anywhere within `import "./a.ncl"` open `a.ncl` and jumps to the beginning of the file, as it used to.

**Environment**
 - Version of the code: 1.3.0-release

**Additional context**

I think we got rid of the old linearizer between 1.2.2 and 1.3.0, so this is the most probable suspect. cc @jneem

**Comment by jneem** [comment]
Huh, I didn't even realize this was a feature. It looks like the cross-file support isn't intrinsically broken, so it shouldn't be hard to fix. For example, going to the definition of `a.foo` here still works:
```
# b.ncl
{
  a = import "a.ncl",
  b = a.foo
}

# a.ncl
{ foo = 1 }
```
