### ISSUE TITLE
Nickel Release 1.4.0 does NOT contain binaries

### ISSUE THREAD

**Issue by uhlajs** [tweag/nickel#1759]
Nickel Release 1.4.0 does NOT contain binaries.

Same issue as for 1.3.0 [here](https://github.com/tweag/nickel/discussions/1713#discussioncomment-7679791).

**Comment by vkleen** [comment]
Yeah, I think our AWS spot runner got canceled again... I'll try to fix this.

**Comment by vkleen** [comment]
Binaries are up :tada:
