### ISSUE TITLE
Cannot build using nix-shell

### ISSUE THREAD

**Issue by maciej-trebacz** [tweag/nickel#177]
**Describe the bug**
Trying to build Nickel using the instructions provided in README using nix doesn't work, running `nix-shell` gives the following error message:

```
error: --- UsageError ----------------------------------------------------------------- nix-shell
nix-shell requires a single derivation
Try 'nix-shell --help' for more information.
```

**To Reproduce**
1. Have Nix installed
2. Clone the repository and enter the nickel directory
3. Run `nix-shell` command

**Expected behavior**
A shell should spawn with all dependencies installed to build Nickel.

**Environment**
 - OS name + version: macOS 10.15 Catalina
 - Version of the code: master branch, bef3c14
 - Nix version: nix (Nix) 3.0pre20200820_4d77513

**Comment by regnat** [comment]
It looks like the flake only defines outputs for `x86_64-linux` (https://github.com/tweag/nickel/blob/master/flake.nix#L44-L50). I'm not fluent-enough in writing flakes to point out the best way of extending that, but I guess it could be done by drawing inspiration from https://github.com/edolstra/dwarffs/blob/master/flake.nix

**Comment by yannham** [comment]
@edolstra, if by chance you're passing by and you have a fix mac users.
