### ISSUE TITLE
Bad error message when enums do not match up

### ISSUE THREAD

**Issue by andreabedini** [tweag/nickel#1771]
**Describe the bug**

When enum do not match up the error is ... bad? 

```
this expression has type Enum, but Enum was expected
```

**To Reproduce**

```
❯ nickel repl
nickel> match { 'a => 1 } 'b
error: dynamic type error
  ┌─ <repl-input-0>:1:1
  │
1 │ match { 'a => 1 } 'b
  │ ^^^^^^^^^^^^^^^^^^^^
  │ │                 │
  │ │                 evaluated to this
  │ this expression has type Enum, but Enum was expected
  │
  = match expects its argument to be a Enum
```

**Expected behavior**

The error is not telling us what the interpreter is actually expecting, mentioning `'a` and/or `'b`.

**Environment**
 - x86_64 GNU/Linux
 - nickel-lang-cli nickel 1.4.0 (rev cargore)

**Comment by yannham** [comment]
Prophetic comment :upside_down_face: 

https://github.com/tweag/nickel/blob/8a1e5387d57a7d621faf3eef3b33e58ba8f1e2e8/core/src/eval/operation.rs#L355
