### ISSUE TITLE
Contract attached to record key not getting evaluated

### ISSUE THREAD

**Issue by suimong** [tweag/nickel#1774]
**Describe the bug**
I'm seeing a weird behavior with v1.4.0 (not sure about how far back it goes though), that contracts attaching to a key is not evaluated, only contracts that attach after the value gets evaluated.

**To Reproduce**
Using the sample code from the [documentation](https://nickel-lang.org/user-manual/correctness/#using-a-contract-annotation-1):

```nickel
# sample.ncl

{
    OptLevel = std.contract.from_predicate (fun value =>
      std.array.elem value ["O0", "O1", "O2", "O3"])
    ,
    level = 4
    ,
    opt_level | OptLevel = "A" ++ std.string.from_number level,
    opt_level2 = ("A" ++ std.string.from_number level) | OptLevel,
}
```

```bash
nickel eval sample.ncl --field=opt_level   # evaluates to "A4", which is wrong
nickel eval sample.ncl --field=opt_level2  # contract broken by a value, which is expected
```

**Environment**
 - OS name + version: NixOS 23.11
 - Version of the code: nickel 1.4.0 (rev 1fa5a79)

**Additional context**

**Comment by yannham** [comment]
This isn't good :upside_down_face: 

After a bit more experimentation, it seems only the `--field` argument is concerned (it was introduced in 1.3, IIRC). A fix is on the way, and this might mandate a 1.4.1 release - silently ignoring contracts is bad.
