### ISSUE TITLE
Nickel Release 1.5.0 does NOT contain binaries 

### ISSUE THREAD

**Issue by uhlajs** [tweag/nickel#1861]
Nickel Release 1.5.0 does NOT contain binaries.

Same issue as for:
- 1.3.0 https://github.com/tweag/nickel/discussions/1713#discussioncomment-7679791.
- 1.4.0 https://github.com/tweag/nickel/issues/175

FYI @vkleen.

**Comment by vkleen** [comment]
Yeah, I was too busy the last week to try fixing the infra again. We need some way of having a test CI task running at regular intervals, so we could spot these things before the release.

**Comment by vkleen** [comment]
Should be addressed by #1863. Nickel 1.5 binaries are being built and should be up in a few hours (someone should really figure out a way to build them statically without rebuilding *all* the toolchains :sweat_smile:)
