### ISSUE TITLE
The Syntax Bikeshedding Dojo, round 3: Merging

### ISSUE THREAD

**Issue by yannham** [tweag/nickel#187]
Follows #183 and #186. The target is the merge operation.

## Context
In Nickel, the merge operation is fundamental. It is used to:
- Combine different records into one. Example: `merge {a = 1; b = {c = true}} {foo = "a"; b = {bar = "b"}}` gives `{a = 1; foo = "a"; b = {c = true; bar = "b"}}`. The idea is to define configurations in a modular way, and compose the pieces easily. Think of mixins in object oriented languages.
 - Verify data against a schema. If the merge operation is used to merge a record with a schema, then contracts are applied, default values are selected, etc. Example: if `x` is `merge {foo = Contract(Num); bar = Default("a")} {foo = false}`, then `x.bar` is `"a"` and `x.foo` gives a blame error, because `false` is reject by the num contract.

Currently, the merge operation is a primitive operator called `merge` and used as a function. This can be ok, but as we expect merging to be used often.

 1. a binary operator could be terser
 2. merging multiple records together is simpler with an infix notation: `merge (merge (...) (...)) (...)` vs `(...) & (...) & (...)`.

## Proposals
I don't have any strong opinion on this, so here is a list of candidates. In CUE, from where this is inspired, merging is actually an intersection - or unification - operation.
- `&`: this the symbol for [unification in CUE](https://cuelang.org/docs/references/spec/#unification). It's also the symbol for intersection types in [Ceylon](https://ceylon-lang.org/documentation/1.3/spec/html/introduction.html#unionandintersectiontypes) or [TypeScript](https://www.typescriptlang.org/docs/handbook/unions-and-intersections.html#intersection-types).
- `^` or `/\` which is the mathematical "meet" symbol of a [lattice](https://en.wikipedia.org/wiki/Lattice_(order)).
- `#`: the picture kinda conveys the idea of "merging", "mashing" or "crossing" things together. It is already used for custom contracts though, so this can become confusing.

Another choice is to keep the `merge` keyword.

**Comment by mboes** [comment]
I think an infix operator is warranted. And `&`, following precedent from CUE, is the option I like most. Unless we make `merge` some kind of magical maximal munch variadic function.

**Comment by gkaracha** [comment]
I agree with @mboes, `&` seems to me like the most intuitive option here, and agrees with my past experience with intersection types.
