### ISSUE TITLE
Encode/decode JSON string

### ISSUE THREAD

**Issue by olorin37** [tweag/nickel#1980]
Stdlib should have functions for encoding object to JSON string and decoding it from string to the object. This is common practical need in configuration. (When as one field JSON string should be provided, regardles if outer format is also JSON or other, like YAML).

**Comment by yannham** [comment]
I think `std.serialize` and `std.deserialize` are what you're looking for. More specifically `std.serialize `Json {hello = "wolrd"}` or `std.deserialize 'Json "{hello = \"world\"}"`

**Comment by olorin37** [comment]
Right, I forgot about the function 🤦‍♂️, sorry for the noise:-)
