### ISSUE TITLE
Expose more math functions

### ISSUE THREAD

**Issue by Hugal31** [tweag/nickel#2005]
**Is your feature request related to a problem? Please describe.**
We are managing the configuration for a robot, and as such, we often need to do computation with angles (for example). However, nickel doesn't expose some useful math functions, such as `sin`, `cos`, `arcsin`, etc... Some math functions are easy to write in nickel but those are not.

**Describe the solution you'd like**

An addition to the std.number module, or a new std.math module containing these functions:
* The trigonometric functions (sin, cos, tan, arcsin, ...)
* The logarithm function (with the base parameter).
* The sqrt function (though you could re-implement it using pow)
* The value for PI (though it's easy to copy in our code).

**Comment by yannham** [comment]
Sure, that would be fine. Would you like to take a stab at implementing this? This should be rather straightforward, by following the example of existing maths functions. Let's add a new primop for each of those functions, as I fear pure Nickel code might be a bit flow at the moment, especially for non trivial maths.

**Comment by Hugal31** [comment]
I'll give it a go!
