### ISSUE TITLE
1.7.0 retag issue

### ISSUE THREAD

**Issue by chenrui333** [tweag/nickel#2019]
👋 seeing the checksum got changed while rebuilding 1.7.0 release, raise this issue to confirm if there was some re-tagging. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/179159

**Comment by chenrui333** [comment]
probably this

<img width="1292" alt="image" src="https://github.com/user-attachments/assets/fa11326f-9478-4b22-9ee9-db685a28ef84">

**Comment by yannham** [comment]
I confirm that we retagged 1.7 just right after the release, because it didn't point to the right revision (it was just missing the version bump mostly, so it would still present as Nickel 1.6 but was 1.7 feature-wise). Sorry for the trouble!

**Comment by chenrui333** [comment]
No worries. Thanks @yannham for confirming it!
