### ISSUE TITLE
Where is  "import" formally documented?

### ISSUE THREAD

**Issue by vi** [tweag/nickel#2033]
I see `let ... = import ... in` several times though the [documentation](https://nickel-lang.org/user-manual/), but don't see a specific page or section regarding modules, imports and multi-file projects. [Standard library documentation](https://nickel-lang.org/stdlib) also does not contain something like an `import` built-in function.

Shall documentation about multi-file Nickel projects be extended?

**Comment by yannham** [comment]
You're absolutely right, it does deserve at least a short paragraph at least somewhere in the doc about its existence and what kind of imports are currently supported. I wonder where would be the best place. It should at least be mentioned in the syntax chapter. But "Modular Configurations" is probably a better place for an extended description.

**Comment by vi** [comment]
I see it can import raw text if I use `.txt` extension.

Can I override the type and import a string from e.g. `mychunk.html`?

I tried `let q : String = import "qqq.html" in q`, but it still results in a `Dyn`.

Maybe it should not fall back to Nickel source code at all on unknown filename extension, showing error message mentioning how to specify the format.

That would also make `import "/proc/self/fd/0"` more useful.

**Comment by yannham** [comment]
Unfortunately the current logic is pretty simplistic and is based on a set of known extensions for common formats (TOML, JSON, text, etc.), and default to Nickel otherwise. See e.g. #1000. A possible syntax is mentioned in #1644 - and the `import` syntax has been mode so that we can enrich it in a backward-compatible way, so something like supporting `import "foo.html" as text` is entirely possible.

**Comment by vi** [comment]
What if make `import` return unspecified type for unrecoginzed filename extensions and use type inference to determine the import type?

This way `let q : String = import "qqq.qqq" in q` would make it import as text, `let q : Dyn = import "qqq.html" in q` would make it import as Nickel.

`let q = import "qqq.qqq" in q` should just err.

**Comment by vi** [comment]
Tried doing `import 'Type "string_literal"`. Seems to be working and looks straightforward.
