### ISSUE TITLE
Building nls with `--no-default-features` fails.

### ISSUE THREAD

**Issue by jneem** [tweag/nickel#2062]
Some APIs changed, and the external formatter doesn't build anymore. We should either fix it (and check in CI that it builds) or remove the option to use an external formatter.

I seem to remember that it was originally made configurable because of some difficulty building pre-releases of topiary. Maybe we don't need the external formatting option anymore?

**Comment by yannham** [comment]
Indeed, I believe this was a fallback when the NLS version published on crates.io didn't include Topiary. The  only reason that I could see for using an external formatter is when you have both Nickel and NLS installed; in this case maybe it's a bit wasteful to have Topiary compiled and included in both, and NLS should use `nickel format` instead? But this is a different motivation, so IMHO it's ok to remove the external formatter feature for now and then decide.
