### ISSUE TITLE
unexpected/unclear single quote behavior

### ISSUE THREAD

**Issue by databasedav** [tweag/nickel#2133]
**Describe the bug**
unclear what the expected single quote behavior is, couldn't find anything relevant in the docs

**To Reproduce**
in `test.ncl`
```
# 1
{
    a = "''"
}
```
```
$ nickel export --format yaml test.ncl
a: ''''''
```
```
# 2
{
    a = "a == ''"
}
```
```
$ nickel export --format yaml test.ncl
a: a == ''
```
```
# 3
{
    a = "{{ a == '' }}"
}
```
```
$ nickel export --format yaml test.ncl
a: '{{ a == '''' }}'
```
```
# 4
{
    a = "${{ a == '' }}"
}
```
```
$ nickel export --format yaml test.ncl
a: ${{ a == '' }}
```
```
# 5
{
    a = "${{ a == '' ? b : c }}"
}
```
```
$ nickel export --format yaml test.ncl
a: '${{ a == '''' ? b : c }}'
```
**Expected behavior**
it's not clear when the yaml output field will be wrapped in single quotes, or when the single quotes get doubled up? the last example (number 5) is especially relevant because this is the conditional syntax for github actions, which i'm generating with nickel

**Environment**
 - OS name + version: `ubuntu 24.04`
 - Version of the code: `nickel-lang-cli nickel 1.9.0 (rev 228712f)`

**Comment by jneem** [comment]
The short answer is that nickel uses `serde_yaml` to render yaml (although this will have to change at some point, as `serde_yaml` is no longer maintained), and whatever string style `serde_yaml` chooses is the one we produce.

I looked a little into how `serde_yaml` makes its decision, and it appears to prefer the "plain" style (i.e. no quotes) unless (1) quotes are necessary to preserve the type, like for a string that could be misinterpreted as a number if quotes are emitted; or (2) there are some special characters that force quotes. In your example number 5, it's the `:` that forces the quotes.

> the last example (number 5) is especially relevant because this is the conditional syntax for github actions, which i'm generating with nickel

Could you elaborate on this? I'm not familiar with the intricacies of how yaml escaping interacts with github actions. For example, my understanding of yaml is that

```
a: '${{ a == '''' ? b : c }}'
```

and 

```
a: "${{ a == '' ? b : c }}"
```

are two different ways of writing the same document. Does github actions treat them differently?

**Comment by databasedav** [comment]
> I'm not familiar with the intricacies of how yaml escaping interacts with github actions

that makes two of us :sweat_smile: 

but I know for sure from my failing CI runs that the former is not valid and returns something along the lines of
```
Unexpected symbol: '?'
```
presumably because the single quote has already been closed? not sure

and if the latter is caused by the `:`, then it seems that a valid github actions flavored ternary can't be produced via nickel when it includes single quotes, i need the `''` in particular for checking for the value of an optional `workflow_call` input parameter

perhaps i can just use the empty string's falsi-ness as a workaround for now

**Comment by jneem** [comment]
Maybe github actions doesn't handle escaped single quotes in single quoted strings? A double-`'` in a single-quoted string is an escaped `'`; it shouldn't end the string. ([Spec](https://yaml.org/spec/1.2.2/#732-single-quoted-style)).

Does exporting as json instead of yaml help? Since json is a subset of yaml github should still accept it, and the escaping rules are much simpler.

**Comment by databasedav** [comment]
the json -> yaml idea sounded promising but :sob: 
```
$ nickel export --format json test.ncl
{
  "a": "${{ a == '' ? b : c }}"
}
$ nickel export --format json test.ncl | yq eval -P
a: '${{ a == '''' ? b : c }}'
```

**Comment by databasedav** [comment]
turns out chatgpt just hallucinated the ternary operator :facepalm: using `a && b || c` works as expected

**Comment by jneem** [comment]
> also if you meant defining workflow files as json, github actions does not accept this (at least according to chatgpt)

json is a subset of yaml: if you take `test.json` and rename it as `test.yaml` it's a valid yaml file, representing the same data that the json file did. So I'd guess that chatgpt is hallucinating here too...
