### ISSUE TITLE
Next batch of functions for the standard library

### ISSUE THREAD

**Issue by yannham** [tweag/nickel#254]
The current standard library is very minimalist. Let's add a new batch of functions and modules. This scope of this issue is to gather proposals, discussions and track progress on implementation. The idea is not to have a perfect, final version of the stdlib but rather to provide all the basic functionalities required for a first release of Nickel, without crippling holes in it.

Functions are grouped by modules, which may not exist yet. ~~List functions are typed with the current monomorphic list type (with `Dyn` pretty much everywhere), but will obviously be patched after #171.~~ [Edit: now merged]

## Builtins
- [x] `id : forall a. a -> a`
- [x] `hash : Dyn -> Str -> Str` (like Nix `builtins.hash`)
- [x] ~`toJSON : Dyn -> Str`~ `serialize : <Json, Yaml, Toml> -> Dyn -> Str`, or alternatively `#Serializable -> Str` with an appropriate `Serializable` contract
- [x] ~`fromJSON : Str -> Dyn`~ `deserialize : <Json, Yaml, Toml> -> Str -> Dyn`
- [x] `typeOf : Dyn -> Str`

## Contracts
- [x] `#Int`
- [x] `#Nat`
- [x] `#NonZero`
- [x] `#NonZeroNat`
- [x] `#NonEmptyStr`
- [x] `#NonEmptyList`

## Numbers
- [x] `max/min: Num -> Num -> Num`
- [x] `floor: Num -> Num`
- [x] `isInt: Num -> Bool`

## Lists
- [x] `elem : forall a. a -> List a -> Bool` (is member of)
- [x] `partition : forall a. (a -> Bool) -> List a -> {in: List a, out: List a}` (open to other field names)
- [x] `sort : forall a. (a -> a -> Bool) -> List a -> List a`
- [x] `generate : forall a. (Num -> a) -> Num -> List a` or `forall a. (#Nat -> a) -> #Nat -> List a`.  Generate a list from a generator and a length. May be deprecated by list comprehensions.

## Records
- [x] `valuesOf : { | Dyn} -> List`

## Strings
- [x] `join : List Str -> Str -> Str`
- [x] `split : Str -> Str -> List Str`
- [x] `trim: Str -> Str`
- [x] `uppercase: Str -> Str`
- [x] `lowercase: Str -> Str`
- [x] `contains: Str -> Str -> Bool`
- [x] `replace : Str -> Str -> Str -> Str`
- [x] `match : Str -> Str -> ?` match a regular expression. Return type could be either a list of matched subgroups or null as in Nix, or a more structured match object.
- [x] `length : Str -> Num` or `Str -> #Nat`
- [x] `substring : Num -> Num -> Str -> Str` or `#Nat -> #Nat -> Str -> Str`
- [x] ~numToString~ `fromNum : Num -> Str`
- [x] ~enumToString~ `fromEnum : forall a. < | a> -> Str`
- [x] ~boolToString~ `fromBool :  Bool -> Str`
- [x] `toNum : Str -> Num`
- [x] `toBool : Str -> Bool`. We could refine the input type of last ones using a contract `NumLiteral`, `BoolLiteral` for the input

**Comment by blaggacao** [comment]
Maybe inspiration: http://docs.jsonata.org/string-functions (not only string functions)
