### ISSUE TITLE
Associative Array Merges

### ISSUE THREAD

**Issue by blaggacao** [tweag/nickel#255]
A part from 
https://github.com/tweag/nickel/blob/9a3f5e7f4a892e28f3137e8490bad1650a7fb01b/src/merge.rs#L26

I couldn't find any reasoning about nickel's take on associative array merges or in general array merge strategies.

This is a very common use case for k8s yaml configurations, and being able to encode the merge strategy as metadata on an array data-structure seems important to me for a config management language with merge semantics.

Maybe I wasn't just able to infer nickel's stance on this topic?

```yaml
- name: "foo"
  thing: "bar"
```
merges with 
```yaml
- name: "foo"
  aspect: "qux"
```
to 

```yaml
- name: "foo"
  thing: "bar"
  aspect: "qux"
```
when associative array merge strategy is configured as:
`mergeKey: name`

**Comment by blaggacao** [comment]
This is also a pre-requisite for semantic diffing.

**Comment by yannham** [comment]
Merging is indeed defined in a non trivial way only for records, the idea being that this merge strategy is the expected natural way of merging dictionnaires, while other data types (such as lists) may have several possible strategies, none of which being THE natural and expected one.

As you point out, it is however often required to combine various data structures in specific ways. The currently favored direction is to add a metadata field to specify a custom merge strategy, giving something like this in practice:

```
let myMerge : Str -> List -> List -> List = fun key l1 l2 =>
 // ... implementation of merging by key..
 in

{
  listOfStuff
    | List
    | merge (myMerge "name")
     = [
      {name = "foo"; thing = "bar"},
      {name = "other"; stuff="stuff"}
     ]
} & {
  listOfStuff = [
    {name = "foo"; thing = "bar"; aspect = "qux"},
  ]
}
// RESULT:
{
  listOfStuff = [
    {name = "foo"; thing = "bar"; aspect = "qux"},
    {name = "other"; stuff="stuff"}
  ]
}
```
This is just an illustrative example, please don't take it too literally (`myMerge` would probably go in a library, the metadata would be better defined in a separate contract than in one of the concrete configuration being merged, we could use a more specific contract than `List` such as `List {name: Str | Dyn}`, etc.).

I'll let this issue open until a concrete proposal is detailed in a fresh issue.

**Comment by yannham** [comment]
Superseded by #330 (and in particular custom merge functions).
