### ISSUE TITLE
Full ASCII Hex escape sequence support for string literals

### ISSUE THREAD

**Issue by blaggacao** [tweag/nickel#256]
**Is your feature request related to a problem? Please describe.**
Current workarounds include:

- https://github.com/numtide/devshell/blob/17f46732ce299daa2977be2978f60d258c2d1b41/mkDevShell/options.nix#L19-L21
- https://github.com/nix-community/home-manager/blob/master/modules/programs/alacritty.nix#L33
  - and then: https://github.com/nix-community/home-manager/blob/3627ec4de58d7fbda13c82dfec94eace10198f23/modules/programs/alacritty.nix#L53-L60

**Describe the solution you'd like**
Add escape sequences for literals addressing them by their ASCII Hex values eg. `\x1B` (`1B` = `<ESC>`)

**Describe alternatives you've considered**
Continue to work around limited ASCII support in literals. See above.

**Additional context**

- https://notes.burke.libbey.me/ansi-escape-codes/
- http://www.asciitable.com

This is especially relevant in the context of configuring input methods &mdash; a supposed first class use case for nickel via nix.

**Comment by yannham** [comment]
Adding this to normal strings is a no brainer. However we previously decided to have only `\#{` (equivalent to Nix's `\${`) as a special escape sequence in multiline strings (cf https://github.com/tweag/nickel/pull/197#issuecomment-726815882). Would that be sufficient to have such escape sequences only work in normal strings? Note that you could still use interpolation then in multiline strings:

```
let esc = "\x1b" in m#"
  ...
  text1 = "#{esc}[38;5;202m"
  ...
"#m
```

@edolstra, any thoughts about this ?

**Comment by blaggacao** [comment]
I see the point there is to make it possible to write (very readable) multiline strings easily with almost no escaping at all permitted.

So your suggestion does not actually feel like a workaround rather like a feature.
