### ISSUE TITLE
The Syntax Bikeshedding Tipi: prefix character for contracts (#)

### ISSUE THREAD

**Issue by yannham** [tweag/nickel#295]
As mentioned by @mboes in https://github.com/tweag/nickel/issues/207#issuecomment-775198557, we may want to follow the convention of using `#` to denote comments. This shouldn't clash with the interpolation syntax which only applies inside strings, but it does clash with the user-defined contract syntax `value | #Contract`.

Another consideration is that other interpolation-ish syntax still uses the old `$`, like dynamically defining a record field from an expression: `{ $"my_" ++ "field" = value }`, or the field removal operator `record -$ field`. It would be nice to use a consistent character/syntax for interpolation, however using `#` for these cases would clash with using `#` for comments. I see the following solutions:

- Keep things as they are
- Find a new character for contracts, set `#` to be comments, and keep the `$` for field interpolation, at the price of some inconsistency.
- Find a new character for both contracts and interpolation, and only use `#` for comments.

It seems `%` is sometimes used for interpolation in templates languages. For contracts, any common prefix character would do: `%`, `@`, `&`, `$`, `~`, etc. Although some may be too closely associated with another semantics in the wild such as `$` for interpolation or `&` for intersection types/merging. In that case, the more neutral ones like `@`, `%` or `~` may be preferable.

**Comment by mboes** [comment]
Agreed. `%` looks reasonable to me.

**Comment by yannham** [comment]
Closed by the uniterm syntax, by #634 and #624. Took `#` for comments, `%` for interpolation, and contracts don't need a character anymore.
