### ISSUE TITLE
nix run fails on macOS

### ISSUE THREAD

**Issue by siraben** [tweag/nickel#308]
**Describe the bug**
Nickel cannot compile when using flakes.

**To Reproduce**
```ShellSession
$ uname
Darwin
$ nix run github:tweag/nickel
```

**Expected behavior**
Nickel should compile and run.

**Environment**
 - OS name + version: macOS Catalina 10.15.7
 - Version of the code:  518716c

**Build log (has terminal escapes)**
```ShellSession
$ curl http://ix.io/2Rrf
```

**Comment by yannham** [comment]
Seems the same kind of bugs as https://github.com/nix-community/nixpkgs-fmt/issues/7. I'll try to add the missing inputs.

**Comment by siraben** [comment]
Thanks, was able to get into a REPL with:

```ShellSession
$ nix shell github:tweag/nickel -c nickel repl
```
