### ISSUE TITLE
Imports are not typechecked

### ISSUE THREAD

**Issue by yannham** [tweag/nickel#316]
**Describe the bug**
Imported files are not typechecked by the interpreter

**To Reproduce**
```
$echo "1 : Str" > bad.ncl
$nickel -f bad.ncl typecheck
error: Incompatible types
  ┌─ nickel/bad.ncl:1:1
  │
1 │ false : Num
  │ ^^^^^ this expression
  │
  = The type of the expression was expected to be `Num`
  = The type of the expression was inferred to be `Bool`
  = These types are not compatible

$nickel typecheck <<< 'let _ign = import "bad.ncl" in 0'
$
```

**Expected behavior**
The typechecker should transitively typecheck imports.

**Additional context**
The problem is that typechecking is done before program transformations, including import resolution, so the typechecker can't have access to the actual content of imports. A corresponding test should have caught that but for some reason it "cheated" and applied program transformations before typechecking. One simple solution is to split program transformations into two passes, import resolution and the rest, and typecheck in between. In the longer term, we probably don't want to traverse the whole term in full just for imports, and may interleave import resolution with either typechecking or parsing.

**Comment by francois-caddet** [comment]
And why not to typecheck in the ImportResolver::resolve?

**Comment by yannham** [comment]
In general I would favor cleanly separated phases, because it is more flexible.

Since Nickel is a dynamic language, it currently type-checks the code at each execution, even when it hasn't changed. While this may be improved on its own, we can imagine nonetheless having a flag at some point to disable typechecking for performance reasons, in which case we would need to do import resolution but not typechecking.

Another reason is that the typechecker may need the type of an import inside a file, that is, typechecking may need to access more than just the current file in order to proceed. For example, to typecheck the following:

```
let someValue : Num =
  let module = import "foo.ncl" in
  module.someFunction "a" "b"
in ...
```

The type-checker needs to have access to the type of "foo.ncl" to know that it as indeed a field `someFunction` that is a function of type `Str -> Str -> Num`. To do so, it needs the import to have been resolved.

On the other hand, I don't really see a good reason for typechking inside `ImportResolver::resolve`. Sometimes mixing phases like this can allow to reduce the number of passes, but it is not the case here, because typecheck would re-traverse the new import anyway.

As mentioned in the issue, other approaches include:
- do import resolution during parsing, which would be potentially more efficient by avoiding to re-traverse the AST just to resolve imports, but I don't know how that would play with LALRPOP.
- do import resolution lazily, that is either when the typechecker or the evaluator actually needs to resolve an import. This has the advantages of not loading and parsing unused files when typechecking is disabled (which I don't know if it is very important in practice). On the other hand it would make typechecking less obviously parallelizable (import resolution either needs to mutate the AST in-place as currently, or to access an external, shared cache in one way or another), so it is not totally free either. Because typechecking needs to traverse all the imports anyway, I don't think it is really worth the trouble for now. It may change in the future if we get a smarter, more incremental typechecking process that e.g. wouldn't recheck imports that haven't changed.
