### ISSUE TITLE
Show type information in a query

### ISSUE THREAD

**Issue by yannham** [tweag/nickel#368]
**Is your feature request related to a problem? Please describe.**
The `query` command currently doesn't show the type of the queried expression, when available:

```
$ nickel query <<< lists.map
• value: <func>
```

**Describe the solution you'd like**
The `query` command should show at least type annotations:

```
$ nickel query <<< lists.map
• type: forall a b. (a -> b) -> List a -> List b
• value: <func>
```

**Comment by edolstra** [comment]
@yannham Can you resolve the merge conflict?
