### ISSUE TITLE
Interpreter panics on contracts with unbound type variables

### ISSUE THREAD

**Issue by yannham** [tweag/nickel#384]
**Describe the bug**
If one enforces a contract written as a type where some type variable is unbound, the interpreter panics when it tries to elaborate this contract as a concrete term.

**To Reproduce**

```
nickel> 1 | a
thread 'main' panicked at 'Unbound type variable Ident("a")', src/types.rs:202:40
```

**Expected behavior**
Two alternatives:

1. Unbound type variables should be checked at parse time, or at least during typechecking, even for types only used as contracts.
2. Automatically generalize unbound type variable, so that one could write `fst: a -> a -> a = fun x y => x` to mean `fst: forall a. a -> a -> a = fun x y => x` as in e.g. Haskell. With this, no more unbound type variables.

**Additional context**
Another related quirk: currently the parser accepts any word as a type variable. This can lead to puzzling errors:

```
nickel> 1 | num
thread 'main' panicked at 'Unbound type variable Ident("a")', src/types.rs:202:40
```

Here, if the user write `num` instead of `Num`, it is considered as a type variable. With the proposal 2. above, this won't be an error anymore, but would be elaborated as `1 | forall num. num`, which is questionable, to say the least. The conclusion is that type variables should be only 1-character.

**Comment by regnat** [comment]
> The conclusion is that type variables should be only 1-character.

I’m not sure it has to be that strict. If the error message shows the name of the type variable, it should be OK:

```
nickel> 1 | num
thread 'main' panicked at 'Unbound type variable Ident("num")', src/types.rs:202:40
```

`ghc` does that, and I don’t think it’s considered as an issue:

```
Prelude> 1 :: int

<interactive>:1:1: error:
    • No instance for (Num int1) arising from the literal ‘1’
      Possible fix:
        add (Num int1) to the context of
          an expression type signature:
            forall int1. int1
    • In the expression: 1 :: int
      In an equation for ‘it’: it = 1 :: int
```

(And even the case where it’s interpreted as `1 | forall num. num` should eventually raise a good-enough error message in most cases)

**Comment by yannham** [comment]
> I’m not sure it has to be that strict. If the error message shows the name of the type variable, it should be OK

Fair enough, that does sound reasonable!

**Comment by aspiwack** [comment]
I favour (1).
