### ISSUE TITLE
Nickel flake doesn't build on Hydra

### ISSUE THREAD

**Issue by edolstra** [tweag/nickel#387]
**Describe the bug**

The nickel flake does not evaluate on Hydra because it uses import-from-derivation. See https://hydra.nixos.org/jobset/flakes/nickel#tabs-errors:

```
in job ‘x86_64-linux.nickel-against-beta-rust-channel’:
error: attempted to realize '/nix/store/pqp5b30zrplspxvf34j6rx7cdd29iqw3-channel-rust-beta.toml.drv' during evaluation but 'allow-import-from-derivation' is false

in job ‘x86_64-darwin.nickel-against-nightly-rust-channel’:
error: attempted to realize '/nix/store/w01i2apj3bkrh5dzfcbnm0jdc9rb1zvl-channel-rust-nightly.toml.drv' during evaluation but 'allow-import-from-derivation' is false

in job ‘x86_64-linux.nickel-against-stable-rust-channel’:
error: attempted to realize '/nix/store/rx5wypcc50cjhysglr7mj1p6xcx11q51-channel-rust-stable.toml.drv' during evaluation but 'allow-import-from-derivation' is false

in job ‘x86_64-darwin.nickel-against-beta-rust-channel’:
error: attempted to realize '/nix/store/j8m8yykbbk9lglla4jykdf2gn895gakj-channel-rust-beta.toml.drv' during evaluation but 'allow-import-from-derivation' is false

in job ‘x86_64-darwin.nickel-against-stable-rust-channel’:
error: attempted to realize '/nix/store/aq1xnj7k3s0y8pfryq3ia9f4hv5klas3-channel-rust-stable.toml.drv' during evaluation but 'allow-import-from-derivation' is false

in job ‘x86_64-linux.nickel-against-nightly-rust-channel’:
error: attempted to realize '/nix/store/ad9gjv42mip62n4wiqm4cj4lkncslp36-channel-rust-nightly.toml.drv' during evaluation but 'allow-import-from-derivation' is false
```

Building the nickel flake is advantageous because it populates cache.nixos.org, so commands like `nix develop` don't have to build dependencies locally.

**To Reproduce**

Run
```
$ nix flake check --no-allow-import-from-derivation
error: attempted to realize '/nix/store/rx5wypcc50cjhysglr7mj1p6xcx11q51-channel-rust-stable.toml.drv' during evaluation but 'allow-import-from-derivation' is false
(use '--show-trace' to show detailed location information)
```

**Expected behavior**

Import-from-derivation should be avoided since Hydra doesn't support it and it's generally a bad idea.

**Environment**
 - OS name + version:
 - Version of the code: 086e1c20b69260d57f2585f7a8a4e732a8a8550c

**Comment by yannham** [comment]
I'm not so familiar with the mozilla Rust overlays, which seems to cause the issue. Do you have any suggestion for a IFD-free route?

**Comment by silverraven691** [comment]
> in job ‘aarch64-linux.nickel-against-stable-rust-channel’:
> error: access to URI 'https://static.rust-lang.org/dist/2021-11-01/channel-rust-stable.toml' is forbidden in restricted mode

#463 did fix one issue bit broke something else, I'll have a look at switching to `fenix`.

**Comment by silverraven691** [comment]
@yannham Could this be re-opened, please?
