### ISSUE TITLE
`import`s are always inferred as `Dyn`

### ISSUE THREAD

**Issue by regnat** [tweag/nickel#430]
(I think this is essentially a more generic version of https://github.com/tweag/nickel/issues/375 − and is hopefully fixed by #392, but since the symptoms aren’t obviously related it’s worth its own issue)

**Describe the bug**

`import "foo.ncl"` is always given the `Dyn` type regardless of what’s in `foo.ncl`

**To Reproduce**

```console
$ cat <<EOF > imported.ncl
{ foo = "bar" } : { foo : Str }
EOF
$ nickel -f imported.ncl typecheck
$ cat <<EOF > main.ncl    
> let Imported = import "imported.ncl" in
> Imported.foo : Str
> EOF                                                                                                        
$ nickel -f main.ncl typecheck
error: Incompatible types
  ┌─ /tmp/tmp.iXrAfpc3uc/main.ncl:2:1
  │
2 │ Imported.foo : Str
  │ ^^^^^^^^ this expression
  │
  = The type of the expression was expected to be `{foo: Str | _a}`
  = The type of the expression was inferred to be `Dyn`
  = These types are not compatible
```

**Expected behavior**

`import "imported.ncl"` should have the same type as the equivalent inlined expression (so `{ foo : Str }` in this case)

**Environment**
 - OS name + version: NixOS 21.05
 - Version of the code: c8d608de9649f955f7c5e121b92ac96f01cfa568

EDIT: To be more precise, imports are always **inferred** as `Dyn`, but can be checked against a more precise type. For example `let Imported : { foo : Str } = import "imported.ncl" in Imported.foo : Str` typechecks just fine

**Comment by francois-caddet** [comment]
Can be closed right?
