### ISSUE TITLE
Go to reference/definition does not work for contracts

### ISSUE THREAD

**Issue by yannham** [tweag/nickel#442]
**Describe the bug**
The go to reference/definition does not work when a variable is used as a contract annotation.

**To Reproduce**

```
let DummyContract = fun _label value => value in
{
  foo | #DummyContract = "bar",
}
```

If we hover somewhere on `#DummyContract` and try to go to definition, it doesn't find anything.

**Expected behavior**
The second occurrence `#DummyContract` should be seen as a usage, and refers to the definition of `DummyContract`.

**Environment**
 - Version of the code: c94a4c3a6c42b8b81d03ef5943de22f4fc11c887

**Additional context**
The issue is probably that the LSP doesn't take terms that are wrapped inside a type `Flat` into account, while it should.

cc @ysndr

**Comment by ysndr** [comment]
Contracts or more precisely metadata of record fields are not yet indexed. In fact I'm working on that right now so this will be addressed soon.
