### ISSUE TITLE
Checking records

### ISSUE THREAD

**Issue by teofr** [tweag/nickel#45]
_This is mainly intended as a discussion point on how to check records_

Nix has some kind of checking on records, in particular argument set (pattern matching +/-), and some coding folklore built around these. 

In particular you can pattern match on records on two different ways:
 * Closed (non-variadic), which means we state exactly what fields a record should have.
 * Open (variadic), which means we state some fields that the record must have (it may have more)

On the blame calculus we're developing, a contract has to check two different things, what the value looks like, and how it's used. Ideally we want to follow the above idea of two kinds of records, but came the moment to ask ourselves, how these two can be treated.

On the following table, each row states how a record can be used, while each column how it should be constructed. And on each cell we position a different contract

_record contracts_ | closed fields | open fields
-------------------------- | :---: | :---:
**closed usage**    | non-variadic | A
**open usage**       | B                  | C

It's pretty clear that a non-variadic argument set is closed in both axes, and it's pretty clear that B is useless. However, it's not so clear whether a variadic argument set goes on A or C.

Arguments in favor of A:
 * We would use this contract to close the scope of a record, keeping only a few of it's elements. This makes sense, for instance, if we were to keep some fields private (inaccessible) without actually copying the whole thing

Arguments in favor of C:
 * We would use this contract to apply some constraints on a record, but allowing access to (unknown) fields.

Following @regnat's work on nix [Section 3.3.2](https://www.docdroid.net/BWWJov0/main.pdf#page=14) it seems a good solution to allow a catch-all field on a record type, for instance, an A type would look like `{a: Num, b: String, _ : Dyn}` or even `{a: Num, b: String, _ : Bool}`. And a C type would look like `{a: Num, b: String, _ : Void}`.

If we were to add a special contract (type) to signal unexistent fields (Δ), we could write non-variadic records as `{a:  Num, b: String, _ : Δ}` (we need this because otherwise the evaluation is not forced).

cc @aspiwack 

TODO:
 * Understand and register how Flow (and maybe Typescript) does this.
 * Understand how typechecking would work on this scenario

**Comment by yannham** [comment]
Closing old stale issue. Ideas mostly implemented (see #158).
