### ISSUE TITLE
Pipe operator (not the one we have, but reverse application)

### ISSUE THREAD

**Issue by yannham** [tweag/nickel#455]
**Is your feature request related to a problem? Please describe.**
It often happens that you want to apply several operation to a value in a row. In the current state, this leads to a verbose sequence of let in:

```
let list = [1, 2, 3, 4, 5] in
let list = lists.map (fun x => x + 1) list in
let list = lists.filter (fun x => x > 2) list in
lists.partition (fun x => x % 2 == 0) list
```

**Describe the solution you'd like**
A "reverse application operator", or pipe operator, as OCaml's `|>`. We already have `|` quite overloaded, so I propose to use something else, like `$>` (but that's just a suggestion on the fly). We could have the symmetric sibling `<$` too. This would have the following semantics: `x $> f` is `f x`. It is left associative, such that `x $> f $> g $> h` is `h (g (f (x)))`. The example becomes:

```
[1,2,3,4,5]
$> lists.map (fun x => x + 1)
$> lists.filter (fun x => x > 2)
$> lists.partition (fun x => x % 2 == 0)
```

**Describe alternatives you've considered**

- Point-free notation as in Haskell. Say we have composition operator `.` such that `f . g ` is `fun x => f (g x)`, then that would give:

  ```
  (lists.partition (fun x => x % 2 == 0)
  . lists.filter (fun x => x > 2)
  . lists.map (fun x => x + 1)) [1, 2, 3, 4, 5]
  ```

  However, it reverses the order of transformations (flowing right-bottom to top-left). The pipe operator is usually better at concisely expressing a sequence of transformations, IMHO.

**Comment by aspiwack** [comment]
> pipe operator, as OCaml's `|>`.

As a historical note, this particular syntax has initially been introduced by F# as far as I'm aware. Before Ocaml at least. Haskell uses `&`.

I think `|>` is pretty good syntax, actually. I don't think that it visually conflicts with other uses of `|`.
