### ISSUE TITLE
[Dogfooding] Escaping enums

### ISSUE THREAD

**Issue by yannham** [tweag/nickel#460]
**Is your feature request related to a problem? Please describe.**
While dogfooding on the [mantis repo](https://github.com/input-output-hk/mantis-ops), there are several fields with a finite say of strings as possible values (ex: [here](https://github.com/input-output-hk/mantis-ops/blob/81ad4cb0ec5ff9faeb9065a2ddac060cef6452ac/schemas/nomad/types.cue#L54)). It's nice to represent this type/contract with enums in Nickel, like:

```
{
  protocol | <http, ftp, https>
}
```

As the typechecker is then aware of those, can check match exhaustiveness, and so on. However it isn't possible when one of the alternative is not syntactically an identifier.

**Describe the solution you'd like**
Having a way of escaping non-identifier characters inside enum tags, e.g. by surrounding them by quotes:

```
{
  operator | <"Foo!bar", "Foo!baz", "!="> = `"Foo!bar",
}
```

**Describe alternatives you've considered**
We can also encode this using a custom contract (most probably, this kind of combinator will be in the stdlib at some point):

```
let IsIn = fun values label value =>
  if lists.elem value values then 
    value 
  else
    contracts.blame label
in
{
  operator | #(IsIn ["Foo!bar", "Foo!baz", "!="])
}
```

But:

1. It is less consistent (some enums will be defined with the builtin type, some others with this custom contracts, without beginners knowing why, maybe)
2. As mentioned, the typechecker don't know what to do with that (no match, no typechecking, no pattern matching exhaustiveness, etc.)

A counter-argument could be that enums are meant for things that resembles simple labels, and if one of the alternative for a field is `"!="`, then maybe it shouldn't be encoded as an enum to begin with.

**Comment by regnat** [comment]
I definitely agree that enums only make sense in Nickel if they can be arbirtary strings.
I’m not sure what the exact reasons for not being able to express union of strings at type-level without needing a separate data-type are (but I’m pretty sure there are reasons), but if we go for labels, then I agree that we need to make them arbitrary.

**Comment by francois-caddet** [comment]
Even for ident we could add the possibility to escape name by `"`. Is it a good idea?
Something like `let \`"my var" = 123`. I'm prety sure some languages have this feature. I think, it make the syntax evyer so will not be used unnecessarily.
What do you think?

**Comment by yannham** [comment]
> I’m not sure what the exact reasons for not being able to express union of strings at type-level without needing a separate data-type are (but I’m pretty sure there are reasons), but if we go for labels, then I agree that we need to make them arbitrary.

Good question. My first thought is it has to do with type inference and subtyping. If you want you string literal `"foo"` to be used both as a `Str` and a `<foo | _a>`, and also has its type inferred automatically, I guess you need to infer the latter and have a rule `<x1, .., xn | tail> <: Str` in one form or another. However, if we manage to implement some subtyping with bidirectional type inference, I imagine this would be an attractive solution, avoiding the use of a separate type constructor.

**Comment by yannham** [comment]
>Even for ident we could add the possibility to escape name by ". Is it a good idea?
Something like let `"my var" = 123. I'm prety sure some languages have this feature. I think, it make the syntax evyer so will not be used unnecessarily.
What do you think?

I understand the need for this in record fields and enum tags, are those are values that end up in the end output, and thus whose names may be dictated by external tools consuming this configuration. However, let-bindings strictly stay internal to Nickel programs, so what would be the motivation for allowing exotic identifiers?
