### ISSUE TITLE
Better error message for missing field definition ("empty metavalue")

### ISSUE THREAD

**Issue by yannham** [tweag/nickel#480]
**Is your feature request related to a problem? Please describe.**
When applying a contract-as-a-record to a value, if we try to access a field that is required by the contract but is not defined by the value, we hit the following puzzling error message:

```
nickel> let Contract = {foo | Dyn}
nickel> let data | #Contract = {}
nickel> data.foo
error: empty metavalue
  ┌─ repl-input-0:1:17
  │
1 │ let Contract = {foo | Dyn}
  │                 ^^^^^^^^^ here
```

Beside the error message being unhelpful, the main issue is that this error shows the location of the definition of the contract, but we have no idea where is the problematic **value**. The same contract could literally be applied to hundreds of different values, for all we know. Moreover, it doesn't show when the contract has been applied to the specific value either.

**Describe the solution you'd like**
A clearer error message (like `missing definition for required field bar`), as well as the location of the value that is missing this definition. Additionally, having the location of where the original contract is applied to this particular value may also be helpful.

**Additional context**
The implementation is not totally straightforward. The reason for this message is that when we finally try to unwrap the metavalue and find it is not defined, we already forgot the following pieces of information:

1. What field we were projecting (here, `foo`)
2. The label of the application of the contract to the value (here, corresponding to `data | #Contract`.

We need to remember these things in one way or another (the callstack, checking right after projecting that the value is not an empty metavalue, etc.)

**Comment by litchipi** [comment]
As I'm working on #470 by implementing Closures, I bring Closures into typechecking errors too, so with the environments embedded.
Is this error on a typecheck level ? If we cannot get all informations from the environment, we could maybe store the valuable informations somewhere in the environment embedded in each Closures

**Comment by yannham** [comment]
> Is this error on a typecheck level ? If we cannot get all informations from the environment, we could maybe store the valuable informations somewhere in the environment embedded in each Closures

This issue is orthogonal to typechecking. It's a purely runtime/contract thing.
