### ISSUE TITLE
[Dogfooding] Improve error messages for some record contract violations

### ISSUE THREAD

**Issue by yannham** [tweag/nickel#517]
**Is your feature request related to a problem? Please describe.**
When applying a contract written as a record to a value, the implementation is mostly to merge the contract with the value (although with a few minor differences). If the value is not a record, then the error obtained is then `Non-mergeable terms`, which is slightly unintuitive.

That is, non-record contracts violation and record contract violation give different error messages:

```
let Contract = contracts.fromPred (fun x => builtins.isNum x && x % 2 == 1) in
null | #Contract
error: Blame error: contract broken by a value.
  ┌─ :1:1
  │
1 │ #Contract
  │ --------- expected type
  │
  ┌─ repl-input-3:2:1
  │
2 │ null | #Contract
  │ ---- evaluated to this expression

note: 
  ┌─ repl-input-3:2:8
  │
2 │ null | #Contract
  │        ^^^^^^^^^ bound here

nickel> let Contract = {foo | Num} in
null | #Contract
error: Non mergeable terms
  ┌─ repl-input-2:1:16
  │
1 │ let Contract = {foo | Num} in
  │                ^^^^^^^^^^^ with this expression
2 │ null | #Contract
  │ ^^^^ cannot merge this expression
``` 

**Describe the solution you'd like**
That record contract violation gives a standard blame error message when the operand is not a record.

**Comment by steshaw** [comment]
Updating the examples for the latest `master` and stdlib.

Here we have a non-record contract which issues the expected error message for an incorrect value:

```
nickel> let Contract = contract.from_predicate (fun x => builtin.is_num x && x % 2 == 1) in
null | Contract
error: contract broken by a value
  ┌─ :1:1
  │
1 │ Contract
  │ -------- expected type
  │
  ┌─ repl-input-4:2:1
  │
2 │ null | Contract
  │ ^^^^ applied to this expression

note: 
  ┌─ repl-input-4:2:8
  │
2 │ null | Contract
  │        ^^^^^^^^ bound here
```

The record contract continues to show the non-intuitive "non mergeable terms" error message

```
nickel> let Contract = {foo | Num} in null | Contract
error: non mergeable terms
  ┌─ repl-input-6:1:16
  │
1 │ let Contract = {foo | Num} in null | Contract
  │                ^^^^^^^^^^^    ^^^^ cannot merge this expression
  │                │               
  │                with this expression
```

**Comment by steshaw** [comment]
Thanks 😅
