### ISSUE TITLE
Improve error message for empty doc string

### ISSUE THREAD

**Issue by tsmanner** [tweag/nickel#521]
**Is your feature request related to a problem? Please describe.**
An empty `doc` string was buried in some nickel code somewhere, leading to a crash when evaluating the expression.  `nickel typecheck` has no problem with `doc ""` but other commands produce an error message which doesn't clearly indicate what, or even where, something is wrong.

Given the file `foo.ncl` with these contents
```ncl
{
  foo
    | doc ""
    = "bar",
}.foo
```

The following is the result of invoking nickel:
```
-> nickel --file foo.ncl typecheck
-> nickel --file foo.ncl
Done: ParseError
-> nickel --file foo.ncl export
error: non serializable term
  ┌─ <unknown> (generated by evaluation):1:1
  │
1 │ <parse error>
  │ ^^^^^^^^^^^^^
```

**Describe the solution you'd like**
Ideally, the error message would say something like "error: empty doc string" and print the line:column of the offending input.
At minimum, a line:column would at least point at something that can be fiddled with to fix the problem.

**Describe alternatives you've considered**
Not using `doc` anywhere.
Writing a grep or sed program to report empty or missing doc strings.

**Additional context**
A little extra musing on the topic: it seems to me that `nickel typecheck` should complain about the empty docstring, even if it crashes in the same way.  I understand that the `doc` stuff isn't part of the type system, so it doesn't necessarily make sense for it to produce an error, but the message from `export` is a parse error.  That confuses me a bit, because it implies that `typecheck` uses a different parser than the rest of nickel.

**Comment by yannham** [comment]
Thanks for reporting. It sounds like yet another avatar of error-tolerant parsing. We added support for this in #456 to have the LSP still works fine when part of the source file can't be parsed. But for some reasons error-tolerant parsing seems to be activated in other places, while it was really meant to be used only for the LSP.

On current master (df33c022c30ff40f7dbd565a181c7df1fec08536), if I try a similar example in the REPL, I get a parse error instead:
```
nickel> let foo | doc "" = 1
error: Unexpected token
  ┌─ repl-input-0:1:16
  │
1 │ let foo | doc "" = 1
  │                ^
```

It could be improved, but this is at least much better than what the issue reports.
cc @Avi-D-coder

**Comment by tsmanner** [comment]
Yeah, that's much better.  I'm on `66ba798` which is a couple days old.  On `df33c02` the error message from running nickel on a file are better, but still not all that informative:

`let_in.ncl`:
```ncl
let foo | doc "" = "bar" in
foo
```
Output:
```
-> nickel --file let_in.ncl 
Done: RichTerm { term: ParseError, pos: Original(RawSpan { src_id: FileId(1), start: ByteIndex(0), end: ByteIndex(31) }) }
-> nickel --file let_in.ncl export
error: non serializable term
  ┌─ .../let_in.ncl:1:1
  │  
1 │ ╭ let foo | doc "" = "bar" in
2 │ │ foo
  │ ╰───^
```

Importing the file is, interestingly, flipped.  Importing from another nickel file reports the non serializable term error, but importing from the REPL just says `<parse error>`

```
-> nickel repl
nickel> import "let_in.ncl"
<parse error>

nickel>
```

**Comment by Avi-D-coder** [comment]
I'm about to start debugging this. I don't expect it's a hard fix.

**Comment by yannham** [comment]
Other case in point: we broke the stdlib (it didn't parse), but didn't even notice (#527), because it was just parsed as parse errors. Thus we are indeed parse error tolerant in places we shouldn't be.
