### ISSUE TITLE
[Tests] Examples are not fully tested

### ISSUE THREAD

**Issue by yannham** [tweag/nickel#522]
**Describe the bug**
Currently, the test suite just tries to evaluate the examples. Nickel being lazy, this doesn't unveil errors that could be buried inside e.g. records or lists. So an example could pass the CI while fail when run with `nickel export`.

**To Reproduce**
Go to the `record-contract` example, and change `apiVersion = "1.1.0"` to `apiVersion = "1.1.0" + 1`. The tests are still passing.

**Expected behavior**
Examples should probably be forced for tests.

**Comment by Avi-D-coder** [comment]
This is sort of related to https://github.com/tweag/nickel/issues/524, and https://github.com/tweag/nickel/issues/523.
With https://github.com/tweag/nickel/pull/541 we get the diagnostic bellow. If we don't want to fully evaluate in batch mode for the same reasons we may not want to in the repl https://github.com/tweag/nickel/issues/524#issuecomment-1005033127, is there any other way we could surface this error without making the user force evaluation? Having to force evaluation to get a type error like this is quite non intuitive even though if it makes sense in the context of lazy contracts.

```
error: Type error
   ┌─ /home/USER/Work/nickel/examples/record-contract/record-contract.ncl:58:16
   │
58 │   apiVersion = "1.1.0" + 1,
   │                ^^^^^^^
   │                │
   │                This expression has type Str, but Num was expected
   │                evaluated to this
   │
   = +, 1st argument
```

**Comment by yannham** [comment]
This issue is a bit different, as the requested changes won't affect the user at all. It's just for the testsuite. Here it is totally fine to force stuff if we have to.
