### ISSUE TITLE
REPL should print the contents of lists and records

### ISSUE THREAD

**Issue by mboes** [tweag/nickel#524]
**Is your feature request related to a problem? Please describe.**
Interacting with the REPL is not as informative as one would expect. Examples:

```
$ nickel repl
repl> [1, 2, 3]
[ ... ]
repl> {x = 1, y = 2}
{ ... }
```

**Describe the solution you'd like**
Compound structures like records and lists should be fully pretty-printed.

**Comment by yannham** [comment]
Said differently, should we have the current output of the `:print` (`:p`) command be the default output of the REPL? Despite the existence of the print command, I agree that the default output is quite useless.

**Comment by yannham** [comment]
@mboes #538 basically uses the `:p` command as the default. However it has the consequence of forcing the evaluation and fully substituting variables inside any term you input in the REPL. Were you aware of the `:p` command? Is it not sufficient and should we still proceed? Ofc ideally forcing stuff doesn't change the semantics but maybe in the future we don't want to do it by default if someone enter something like `import "nixpkgs.ncl" {}` and import a huge, lazy record.

**Comment by aspiwack** [comment]
Ghci uses the same convention (try `let x = 1 : x in x`). So does `nix repl` if I'm not mistaken. I'd say that it's definitely a reasonable choice for now.

We can consider more complex printers later if it turns out that it's a problem.

**Comment by yannham** [comment]
I thought `nix repl` didn't force, so I tried. Actually it does something strange in between, maybe it just forces one level:

```
nix-repl> rec {x = x;}
error: infinite recursion encountered

nix-repl> rec {foo = {bar = foo;};}
{ foo = { ... }; }
```

Even more interestingly, the `:p` command is able to handle this kind of recursion without looping:

```
nix-repl>:p { foo = { ... }; }
{ foo = { bar = «repeated»; }; }
```

Anyway, let's proceed with full evaluation for now and see later indeed.
