### ISSUE TITLE
Split off website into separate repo

### ISSUE THREAD

**Issue by mboes** [tweag/nickel#526]
The repository is already large, especially for such a small project. I don't know how large exactly, but my `.git` after a clone 21MB, so that gives an idea. Big enough that I can very much notice this on my dingy connection and big enough that it would matter for users pinning Nickel to some experimental version during CI. It appears that the reason for this is checked-in generated WASM for the website:

```
$ git rev-list --objects --all   | grep "$(git verify-pack -v .git/objects/pack/*.idx \
           | sort -k 3 -n \
           | tail -10 \
           | awk '{print$1}')"
091422942ff7a93c406fef05a3a7df7f839cb729 website/nickel-repl/nickel_bg.wasm
2a882029fb49f8813745a485d74583a401585ab3 website/nickel-repl/nickel_bg.wasm
340ad01a1138a6ddd5c65d18e554eac1372275fc website/nickel-repl/nickel_bg.wasm
7721ce990263235e04629bd25b4ce311d20028c7 website/nickel-repl/nickel_bg.wasm
eee3bd01feaa0943435e995036d193247709dde4 website/nickel-repl/nickel_bg.wasm
d5fcaac2ca77922d186235da42b651afde1522d8 website/nickel-repl/nickel_bg.wasm
6a0aa6f0fa063e47917d54710ca245e34ab8585a website/nickel-repl/nickel_bg.wasm
080db0ed4892e1d7f7cc2778275d01da3c270bb3 website/nickel-repl/nickel_bg.wasm
ff5378965f0fbf87dce2e0a2ec327d449314f36e website/nickel-repl/nickel_bg.wasm
eb09bc24a82cc6d1e65d5ad07bd810e0824818de website/package-lock.json
```

The website arguably should not be part of the repo to begin with, because any project-specific prose should be in the repo and the other assets need to be updated atomically with Nickel itself.

**Comment by yannham** [comment]
I agree it's heavy and not very modular. That was my initial plan too, but @garbas championed that we should merge the two for better integration IIRC: keep documentation in sync, have CI testing website deployment and have netlify preview for each PR to test in the playground (that's maybe as easy to do even on cross-repo? I have no idea).

Maybe @garbas wants to make those points again, better than I did?

**Comment by mboes** [comment]
@garbas has a point. We do want to be able to make code and documentation changes atomically. Meaning, the docs should stay in this repo. At the same time,

1. we don't want all website assets here, and we should expect that down the road the website will include content that doesn't belong in this repo.
2. we don't want the website to be showing the content from `master`, but rather from the latest release of Nickel, or perhaps several releases + `master`.

So I think we do want to split, the way many other projects do, e.g. ReactJS, ReScript and many others. However, to keep the documentation near the code, we should adopt a setup similar what Terraform does. They have a website repo and a core repo. Some of the content lives in the website repo, some of it in the core repo. They bump a submodule pointer whenever they want to trigger a redeploy of the website following e.g. a new release of Terraform.
