### ISSUE TITLE
Consider performing CI using Rust stable channel only

### ISSUE THREAD

**Issue by mboes** [tweag/nickel#532]
We currently run builds and tests at least 6 times at every push, for each of the 3 Rust channels (stable, beta, nightly) and for two operating systems (ubuntu, macOS). The runtime of workflow jobs have high variation, and CI is only as fast as the slowest job, not to mention eating into our organization-wide [concurrency budget](https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration). The latter isn't really a problem except that macOS slots are scarce.

New Rust stable releases are very frequent (every 6 weeks), and breakage rare (unlike in beta or nightly channels). AFAIK we don't specifically depend on compiler features only available in beta, so like the [Rust book](https://doc.rust-lang.org/book/appendix-07-nightly-rust.html) says, testing against beta is therefore mainly a service to the upstream Rust developers (if an issue arises in beta but not in stable then it's likely a bug in the beta release). I don't know why we furthermore test against nightly. Sounds overkill. That nightly breaks our code whenever it does is entirely expected and not terribly interesting to anyone (either us or upstream).

There is another cost to this: to retain reproducible builds, we automate tracking the head of the respective toolchains. So every day, we have at least one new commit by a bot polluting our Git history. In fact over the past 5 months, 16% of commits have been of this kind. The proportion vastly increases when development slows down. That is then more toolchains we have to push to Cachix every night.

I propose we track only `stable`. Less wasteful. We can keep the channel update workflow for stable. That only creates a bot commit every 6 weeks. I don't know that Nickel is a terribly interesting test case for Rust beta, so I propose we drop that as well as nightly. 

Benefits:
* less compute power required for our CI needs,
* 1-2 minutes shaved off CI on average.

**Comment by yannham** [comment]
Fully agreed. It was proposed a while ago, and the answer was "it's doesn't hurt", but actually it isn't free either, indeed.
