### ISSUE TITLE
Parser generator performance

### ISSUE THREAD

**Issue by teofr** [tweag/nickel#54]
The Makam parser generator takes too much memory. This started as an issue for Circle, but is now an issue for local building as well.

Even if some quick fixes could help, I think the ideal solution would be to generate it on Rust (or even JS) and do some interop. It's also nice to only mantain one grammar.

I'd need to:
 * Understand how JS <-> Makam interop works.
 * Understand how Rust <-> JS interop works.
 * Make the parser on the Rust side (and the AST) an independent library (this is also nice for the project)

cc @aspiwack @astampoulis

**Comment by yannham** [comment]
Closing old stale issues about Makam.
