### ISSUE TITLE
Archive makam specification

### ISSUE THREAD

**Issue by yannham** [tweag/nickel#552]
Originally, @teofr started to implement a runnable specification of the Nickel language in a language called Makam, derivative of lambda prolog. This work is located in `makam-spec`, as well as tests in the CI associated to that specification. However, it hasn't been touched in almost two years, and is very probably totally out of sync with the current state of the project.

I propose to archive this work somewhere else and remove associated actions and workflows. @teofr , would you like to store it in one of your own repo? Otherwise, we can archive it under a repo of the Nickel-lang organization, with a README that is clear about the state of this work.

**Comment by teofr** [comment]
Hey Yann, thanks for doing this, I completely missed the original issue.
