### ISSUE TITLE
Language Server: static access resolved but not found while hoering the element

### ISSUE THREAD

**Issue by ysndr** [tweag/nickel#564]
**Describe the bug**

```nickel 
let x = { y = { z = true } }
in x."y".z
```

Neither `"y"` nor `z` can be used to find their declaration.

Reason for `"y"` : the corresponding linearization would list the `Usage` item and then the `Structure` item corresponding to the literal string "y".

**Comment by ysndr** [comment]
```
adding term: Op2(DynAccess, RichTerm { term: StrChunks([Literal("y")]),}, RichTerm { term: Var(Ident { label: "x",}) } })
```
Note that there is a `DynAccess` mixed in, which was not the case earlier

**Comment by yannham** [comment]
Yes, it should be a static access. There must have been a regression in `build_record` at some point.

**Comment by yannham** [comment]
Sorry, I actually confused building a record with accessing a field. That is, `{"foo" = bar}` should be parsed the same as `{foo = bar}`, but this kind of eliminating non-dynamic stuff whenever possible hasn't been implemented for record *access*. It would totally make sense to do so, especially if that helps the LSP.

**Comment by ysndr** [comment]
Yes I remember adding position info to the newly created record fields at some point
Would be great to have this for record access as well.
Although now i cant tell whether this actually worked before or not.
I assume it didn't after all

**Comment by ysndr** [comment]
Ok, for what i can tell it works now
