### ISSUE TITLE
Cloning and droping of Labels take a schoking amount of time

### ISSUE THREAD

**Issue by Acaccia** [tweag/nickel#603]
**Describe the bug**
Sorting a list currently takes an insane amount of time with Nickel. After generating flamegraphs, we can notice that a big amount of time is spend on cloning and dropping `Label`s, and especially their field `type`.
![fg-label](https://user-images.githubusercontent.com/4235083/152346530-7467926b-6acc-4c51-bcb2-b56fa6bd2192.png)
(complete flamegraph linked in the `Files` section)

**To Reproduce**
In the linked PR (soon to be open), I added a new stupid benchmark sorting a list of 100 elements.
Running it with `cargo bench sort -- --profile-time=120`, we obtain a flamegraph similar to the one linked below.

**Expected behavior**
Better performances by avoiding a lot of clones.

**Files**
[flamegraph-benchmark.tar.gz](https://github.com/tweag/nickel/files/7994645/flamegraph-benchmark.tar.gz)

**Comment by yannham** [comment]
Interesting. I expect such recursive functions on list to perform pretty badly unfortunately, as indeed a lot of contracts and intermediate subcontracts are involved everywhere. On one side, a sorting algorithm is probably clearly not what we want to optimize nickel for in priority (e.g. merging large recursive records should be a much more realistic use-case for generating configuration). What's more, list contracts are currently naive (performing linearly even for access operations), so I don't know if we should spend too much effort in optimizing stuff on lists before having solved this linear penalty.

On the other hand, I wouldn't have expected that cloning labels would be the so costly, so this is still an interesting finding. `Types` currently do not feature sharing, so they are mostly deep-copied. I guess one possibility is to have, as for terms, a `SharedTypes` variant (which would also make sense for typechecking, that probably also copy quite a lot of subtrees). Maybe just making the `types` field of the `Contract` type an `Rc` could show sufficient improvements?
