### ISSUE TITLE
Optional field separators (,)

### ISSUE THREAD

**Issue by Atemu** [tweag/nickel#653]
Currently, you have to use a `,` to separate multiple fields of a record:

```Nickel
{
  foo = 1,
  bar = 2,
  baz = 3
}
```

However, these separators aren't strictly necessary as a `=` must always be preceded by a field name.

This is ugly as hell but theortically still parsable:

```Nickel
{
  foo = 1 bar =
  2
  baz 
  = 3
}
```

It'd be better to make them optional such that you can use them where they improve clarity and/or readability (i.e. `{ foo = 1, bar = 2 }`) but aren't *required* to do so when it's obvious thanks to line separators:

```Nickel
{
  foo = 1
  bar = 2
  baz = 3
}
```

I understand the need for separators like these in languages with imperative elements such as Rust but even widely used modern imperative languages like Kotlin, Swift or TypeScript do not require them.

Are there any cases where leaving out the field separator could cause ambiguity in Nickel?

**Comment by yannham** [comment]
Hello!

> However, these separators aren't strictly necessary as a = must always be preceded by a field name.

Unfortunately, I think this isn't true in the current syntax, as of 0.1.0. Fields name can be annotated with types, contracts, and metadata (default priority, documentation). Take the following example:

```nickel
let bound = 2 in
{
  foo = function.id
  bar | GreaterThan bound = 2
}
```

This could be parsed both as `foo = function.id bar | GreaterThan, bound = 2` or `foo = 1, bar | GreaterThan bound = 2`.

Additionally, a field declaration doesn't necessary have a body `= exp`, as it is the case in record contracts. Even outside of record contracts, you can write this:

```nickel
{
  foo = exp,
  will_be_filled_by_merge_later | Num,
  recursive = will_be_filled_by_merge_later + 1,
}
```

If you remove the commas, the 2 first lines can be interpreted once again either as `foo = exp will_be_filled_by_merge_later | Num, recursive = ...` or as it is written currently with the commas.

As an final note, there is also the field path syntax `{field1.field2.field3 = value}`. If we remove commas, as in `{foo = f bar.baz.foo = 2}`, this means you can't know while parsing the left hand side `bar.baz.foo` if you are parsing multiple field accesses or if you are defining a field by path until you reach an `=`. This doesn't play well the current LALR(1) grammar, which are limited to one character look-ahead. We're not married to an LALR(1) grammar, and this can still be done by parsing such expressions in a common generic structure first and then decide how to interpret it later, but it does bring complexity.

In the end, while this would have been a possible bonus to grab if easy to do, I don't think the expected aesthetic improvement is worth the trouble.

**Comment by indolering** [comment]
As a UX engineer, I’m always a little disappointed when ergonomics aren’t treated as a higher priority in developer tooling. This syntactic choice creates unnecessary busywork when copying and pasting between configs and I really appreciate it in YAML, CUE, INI, Pkl, and TOML.

Dhall and JSON made similar syntactic concessions to parser complexity and the usability cost is real.  It saddens me that my new favorite configuration language is making a similar trade.

**Comment by yannham** [comment]
> As a UX engineer, I’m always a little disappointed when ergonomics aren’t treated as a higher priority in developer tooling. This syntactic choice creates unnecessary busywork when copying and pasting between configs and I really appreciate it in YAML, CUE, INI, Pkl, and TOML.

I'm curious: what's the kind of copy pasting that makes commas annoying on a recurrent basis? I personally had issues when the last comma HAS to be omitted (like in Haskell), but not so much when you can put a comma at the end of an item unconditionally.

**Comment by indolering** [comment]
Allowing commas at the end helps, but I still find comma book-keeping really irritating when dealing with JSON.
