### ISSUE TITLE
Field without definition nor contract are assigned the value `null`

### ISSUE THREAD

**Issue by yannham** [tweag/nickel#697]
**Describe the bug**
One can write field without definitions in Nickel, e.g. for contracts or to indicate that a field is not defined but is expected to be brought by a subsequent merge. Those fields are different from `null`, and are a dedicated construct.

However, if one doesn't specify any metavalue nor a definition, the field is given the value `null` instead of being undefined, which is wrong.

**To Reproduce**
```nickel
nickel>{foo | Num, bar = foo + 1}.foo
error: missing definition for `foo`
  ┌─ repl-input-3:1:1
  │
1 │ ({foo | Dyn, bar = foo + 1}).foo
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^----
  │ │
  │ accessed here
  │ in this record

nickel>{foo, bar = foo + 1}.foo
null
```

**Expected behavior**
A field without an `= exp` right-hand side should not have a definition, and this shouldn't depend on meta-annotations being present or not.

**Comment by steshaw** [comment]
Related:

```
nickel> ({foo : Num} & {foo = 1}).foo
1

nickel> ({foo} & {foo = 1}).foo
error: non mergeable terms
  ┌─ repl-input-2:1:3
  │
1 │ ({foo} & {foo = 1}).foo
  │   ^^^           ^ with this expression
  │   │              
  │   cannot merge this expression
```

I'd expect that the result of `({foo} & {foo = 1}).foo` is 1.

**Comment by steshaw** [comment]
Also,

As expected:
```sh-session
$ ./target/debug/nickel pprint-ast <<< '{foo : Num}.foo'
{ foo : Num  , }.foo
```

but:

```sh-session
$ ./target/debug/nickel pprint-ast <<< '{foo}.foo'
{ foo = null, }.foo
```

I would expect the result here to be `{ foo, }.foo`. So the problem may be rooted in the parser.
