### ISSUE TITLE
Polymorphic contracts don't fail but silently change the semantics

### ISSUE THREAD

**Issue by yannham** [tweag/nickel#727]
**Describe the bug**
Polymorphic functions in statically typed languages (and in the statically typed fragment of Nickel) enjoy a property called [parametricity](https://en.wikipedia.org/wiki/Parametricity). When derived from a static type, a contract tries to dynamically enforce the invariants that would be guaranteed by their static counterpart. Thus, contracts for polymorphic functions enforce parametricity using a technique called dynamic sealing (see for example the [Blame for All](https://dl.acm.org/doi/10.1145/1926385.1926409) paper).

Concretely, polymorphic arguments are wrapped or sealed in a special node (`Wrapped`) when they enter a function, which prevents any inspection. They are unwrapped when exiting the function (either passing the argument to another function of the right type, or when returning a value).

The issue is that in practice, trying to use a wrapped value has surprising and different behaviors. For example, functions operating on `Dyn` values such as `builtin.is_xxx` or `==` won't raise any error, but just return unexpected results. On the other hand, operators that require a specific type for their argument will fail, but often with an unhelpful error message. This is all made worse by the fact that this parametricity issue is not trivial for non FP folks (and even for FP folks!) and uncommon in other languages, so it deserves a particularly good error message.

**To Reproduce**
Trying to use equality on wrapped values just return false without failing:

```
nickel> let peq | forall a. a -> a -> Bool = (==) in peq 0 0
false

nickel>
```

Same for `builltin.is_xxx`, which returns false without failing:

```
nickel> let p_is_num | forall a. a -> Bool = builtin.is_num in p_is_num 0
false

nickel>
```

On the other hand, using a numeric operator gives a (strange) error:

```nickel
nickel>let p_plus | forall a. a -> Num -> Num = (+) in p_plus 0 1
error: type error
  ┌─ <unknown> (generated by evaluation):1:1
  │
1 │ <wrapped>
  │ ^^^^^^^^^ this expression has type Wrapped, but Num was expected
  │
  = +, 1st argument
```

**Expected behavior**
Trying to use (i.e. to evaluate) a wrapped value for anything else than wrapping/unwrapping should raise a proper contract error, referring to the original contract and with proper advice on why the issue is happening.

**Environment**
 - Version of the code: f7e0ced275a71907bfd9b19072bffb92a3c8c376

**Additional context**
This probably implies to store a reference to the original label inside `Wrapped`, and when reaching a wrapped value, checking if the next continuation is a `Wrap/Unwrap` operator to decide if we must stop the execution with a contract error.

**Comment by aspiwack** [comment]
Nice catch.

I wonder if it can be done without every primitive having a special case for `Wrap`? Maybe having a default behaviour for `Wrap` for every `Op`, but give a way to override it? I don't have a good idea on how this could be feasible.

Or make forcing a value to `Wrap` a contract violation. Except in the special unwrapping case. It's kind of awkward too. But maybe less awkward.

**Comment by yannham** [comment]
> Or make forcing a value to Wrap a contract violation. Except in the special unwrapping case. It's kind of awkward too. But maybe less awkward.

That would be my approach too, I think. It's not ideal, but this change sounds the less disturbing.
