### ISSUE TITLE
Error in Row Polymorphism example

### ISSUE THREAD

**Issue by danjl1100** [tweag/nickel#753]
Hello,  Recently, I stumbled upon Nickel in  the [NixOS discourse](https://discourse.nixos.org/t/is-nickel-intended-to-eventually-be-a-nix-lang-alternative-replacement/16087/6), and am pouring through the User Manual documentation. 
I really appreciate how Nickel could help provide reliable diagnostics for error messages, especially for the use case of Nix where so much of the type checking logic occurs in nixpkgs / library code.

Walking through the examples in the user manual, I ran into an issue:

_____

**Describe the bug**
The second example (the **working** example) for the [Row Polymorphism section in the manual](https://nickel-lang.org/user-manual/typing/#row-polymorphism) throws an error on the playground.

Error on [the playground](https://nickel-lang.org/playground):
<details>

```

Nickel Online REPL | Welcome to the Nickel online REPL.
See the output of your snippets here.


nickel> (let addTotal: forall a b. {total: Num | a} -> {total: Num | b} -> Num
  = fun r1 r2 => r1.total + r2.total in
let r1 = {jan = 200, feb = 300, march = 10, total = jan + feb} in
let r2 = {aug = 50, sept = 20, total = aug + sept} in
let r3 = {may = 1300, june = 400, total = may + june} in
{
  partial1 = addTotal r1 r2,
  partial2 = addTotal r2 r3,
}) : {partial1: Num, partial2: Num}
error: function types mismatch
  ┌─ :1:1
  │
1 │ { ... } -> { ... } -> Num
  │ ------- this part of the expected type
  │
  ┌─ :1:1
  │
1 │ { ... } -> { ... } -> Num
  │ ------- does not match this part of the inferred type
  │
  ┌─ repl-input-6:2:5
  │
2 │   = fun r1 r2 => r1.total + r2.total in
  │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ this expression
  │
  = The type of the expression was expected to be `{ ... } -> { ... } -> Num`
  = The type of the expression was inferred to be `{ ... } -> { ... } -> Num`
  = Could not match the two function types

error: While matching function types: ill-formed type
  ┌─ :1:1
  │
1 │ { ... }
  │ ------- ill-formed type

```

</details>

Curiously, I see a different error using the master branch on my machine (run using latest as of writing, f7a99a8853f8fdbf30873e81c2fbf64b2d23aa5d, using nix run on the flake):
<details>

```
$ nix run github:tweag/nickel/f7a99a8853f8fdbf30873e81c2fbf64b2d23aa5d -- repl
nickel> (let addTotal: forall a b. {total: Num | a} -> {total: Num | b} -> Num
  = fun r1 r2 => r1.total + r2.total in
let r1 = {jan = 200, feb = 300, march = 10, total = jan + feb} in
let r2 = {aug = 50, sept = 20, total = aug + sept} in
let r3 = {may = 1300, june = 400, total = may + june} in
{
  partial1 = addTotal r1 r2,
  partial2 = addTotal r2 r3,
}) : {partial1: Num, partial2: Num}
error: unbound identifier
  ┌─ repl-input-15:1:42
  │
1 │ (let addTotal: forall a b. {total: Num | a} -> {total: Num | b} -> Num
  │                                          ^ this identifier is unbound

```

</details>

**To Reproduce**
Run the second example for Row Polymorphism (the **working** example) on [the playground](https://nickel-lang.org/playground)
```
(let addTotal: {total: Num} -> {total: Num} -> Num
  = fun r1 r2 => r1.total + r2.total in
let r1 = {jan = 200, feb = 300, march = 10, total = jan + feb} in
let r2 = {aug = 50, sept = 20, total = aug + sept} in
let r3 = {may = 1300, june = 400, total = may + june} in
{
  partial1 = addTotal r1 r2,
  partial2 = addTotal r2 r3,
}) : {partial1: Num, partial2: Num}
```

**Expected behavior**
I expected the example to work, with no error, as described in the [Row Polymorphism section in the manual](https://nickel-lang.org/user-manual/typing/#row-polymorphism) 

**Environment**
 - OS name + version: [the playground](https://nickel-lang.org/playground)
 - Version of the code: playground appears to be 0.1.0  (different error occurs on f7a99a8853f8fdbf30873e81c2fbf64b2d23aa5d)

**Additional context**
I am just getting started, so I am not sure which version the manual is supposed to work with.
If this is still "in work" then no additional triage is needed.

All the best,
Daniel

**Comment by yannham** [comment]
Hello! The syntax has changed since #595. `|` is not used to delimit tails anymore, but `;` instead (you can find the rationale for those changes in the RFC002 inside `rfcs/`, or look at the linked PR :slightly_smiling_face: ). The correct way to write this example is now:

```nickel
(let addTotal: forall a b. {total: Num ; a} -> {total: Num ; b} -> Num
[...]
```
which works both on master and in the playground.

However, it seems the manual hasn't been correctly updated, which is of course a problem. Will fix this. Thanks for reporting!
