### ISSUE TITLE
LSP panics on records with metadata

### ISSUE THREAD

**Issue by yannham** [tweag/nickel#775]
**Describe the bug**
When opening a Nickel file with an editor using NLS, NLS panics, seemingly if there is any record with a field bearing a annotation with a term inside.

**To Reproduce**
Write the following file:

```nickel
{
  foo | {bar | default = 1} = {},
}
```

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', lsp/nls/src/linearization/mod.rs:119:67
```

**Expected behavior**
NLS shouldn't crash.

**Environment**
 - OS name + version:
 - Version of the code: 8775ece97542b4347b831beb3a808a2ca7577f55

**Additional context**

A git bisect show that the offending commit is e32946f. The issue is probably that the linearization expects record field definition to immediately follow the field declaration, which might be broken by first walking the annotation since e32946f. One fix to try is to first walk the field, and only then the annotation.

**Comment by ysndr** [comment]
I added walking records as well (as far as i remember). maybe there are some conflicting implementations now. can look into this tomorrow.

**Comment by yannham** [comment]
The issue is that the scoping for what's inside the metadata (contracts) is interfering with how record fields are treated (where `scope()` is taking out one single field), because `MetaValue` are moreover treated in a special way (they don't insert any node, they don't pull a potential record field, etc.). Leading to more record fields being popped than actually exist.

My immediate idea (tested, which seems to work) is to add a specific function `scope_meta` for those terms inside metadata to the trait `Linearizer`. What do you think @ysndr ? We also need more documentation about all those invariant that are hard to guess (the one that is currently broken is "after a call to `add_term` on a record must come at most `n` calls to `scope` before the next call to `add_term`, and moreover `add_term` of a static access or a metavalue don't count).
