### ISSUE TITLE
Flake: move from import-from-cargo to cargo2nix

### ISSUE THREAD

**Issue by yannham** [tweag/nickel#813]
**Is your feature request related to a problem? Please describe.**
Currently, the CI is taking ages to run, while Nickel is not really a behemoth. On GitHub, the order of magnitude is a bit less than one hour (45min to 60min, depending on the platform). This is really crippling for our development workflow.

The issue seems to be that every derivation (for Nickel, for the LSP, and for the WASM REPL) is rebuilding everything (in particular, the crates we depend on, and Nickel itself) from source again and again. This is probably due to the way import-from-cargo work, which is quite basic, and which uses fixed output derivation. My current understanding is that this workflow precludes the caching and even the local reuse in-between two builds of Rust crates, including the ones defined  by Nickel.

**Describe the solution you'd like**
Other Tweagers have used cargo2nix internally on another Rust project, with some success. The WASM story might be slightly more complex to pull off, but I expect that as a first step, just moving the build of the nickel-lang and nickel-lang-lsp crates to cargo2nix (while keeping the current infrastructure for WASM) should already improve the situation quite a bit (even without caching, by just reusing the nickel-lang crate as well as the dependencies of nickel-lang in a single build). For the record, they did managed to get a WASM build working with cargo2nix, so it's very much possible. It just probably requires a bit more work.

**Describe alternatives you've considered**
There are other options, like [naersk](https://github.com/nix-community/naersk) or [nocargo](https://github.com/oxalica/nocargo). The latter looks promising but is very ambitious, and I don't think we can count on it in the short term. I don't know much about the difference between naersk and cargo2nix, beside that other Tweagers faced the same choice and chose to go with cargo2nix after considering the options.

**Comment by bew** [comment]
Another alternative is `crane`: https://github.com/ipetkov/crane
> A Nix library for building cargo projects. Never build twice thanks to incremental artifact caching.

**Comment by yannham** [comment]
I haven't heard about this one. Thanks for sharing! Have you used it? Do you know, by any chance, how it compares to cargo2nix or naersk at a very high level?

**Comment by bew** [comment]
I haven't use it yet, but I know I will.
I discovered it through these blog posts from the author:
- https://ipetkov.dev/blog/introducing-crane/
- https://ipetkov.dev/blog/crane-support-for-alt-registries-and-git-deps/

It looks like a nice piece of work, very modular, composable, as all Nix things should be :)

**Comment by sir4ur0n** [comment]
See also this article providing some comparison: https://www.tweag.io/blog/2022-09-22-rust-nix/

**Comment by yannham** [comment]
Superseded by introducing crane in #963 and the remaining tracking issue for the WASM part #967.
