### ISSUE TITLE
The benchmark `typecheck-nixpkgs-lib` does not run

### ISSUE THREAD

**Issue by Acaccia** [tweag/nickel#836]
**Describe the bug**
As of now, there is a parsing error in the Nickel program used for this benchmark:
```
UnexpectedToken(RawSpan { src_id: FileId(8), start: ByteIndex(6569), end: ByteIndex(6577) }, ["\"\\\"\"", "\"..\"", "\";\"", "\"identifier\"", "\"m%\\\"\"", "\"}\""])] }'
```

**To Reproduce**
`cargo bench --bench=typecheck-nixpkgs-lib`

**Expected behavior**
The benchmark should run without issue.

**Environment**
 - Version of the code: 793d3d214b58739ee7d1c1c1c3c546c66f337c76

**Comment by yannham** [comment]
Ah, #829 introduced a new keyword "optional", so the function with the same name causes a parse error. In the future we may want to parse metadata in a nicer way, without reserving tens of keywords, but for the time being, let's just rename this one.

**Comment by yannham** [comment]
Sorry, I meant #815, not 829.
