### ISSUE TITLE
Retry using HAMT as Environment if the closurization model changes.

### ISSUE THREAD

**Issue by Acaccia** [tweag/nickel#837]
**Is your feature request related to a problem? Please describe.**
An HAMT seems like the perfect representation for the evaluation environment. However, PR #822 showed us that the insertion cost was too heavy and this structure was unadapted in our current case.
However, as stated in [this comment](https://github.com/tweag/nickel/pull/822#issuecomment-1243511141), this solution should be tried again if we ever change the closurization model to reduce the number of created variables.

**Describe alternatives you've considered**
This could be an alternative to what is proposed in #807, with the double advantage that we would not have to add a new transformation that the proposed environment would rely on, and it would be a totally transparent change for the actual code.

**Comment by yannham** [comment]
This is superseded by RFC007 (#2045) which will get rid of environments altogether.
