### ISSUE TITLE
Pretty printer identifier quoting is too lax

### ISSUE THREAD

**Issue by vkleen** [tweag/nickel#859]
**Describe the bug**
The pretty printer doesn't quote enough record keys.

**To Reproduce**
```
❯ nickel pprint-ast <<<'{ "priority" = 5 }'
{ priority = 5, }
❯ nickel repl
nickel> { priority = 5, }
error: unexpected token
  ┌─ repl-input-0:1:3
  │
1 │ { priority = 5, }
  │   ^^^^^^^^
```

**Expected behavior**
A pretty-printed AST should always be parsable.

**Environment**
 - OS name + version: NixOS
 - Version of the code: master fcaa7669047b6d80b01d1eebd21c335b5c3dd0a2

**Comment by yannham** [comment]
As Viktor has left, and is unlikely to make this progress, I'm going ahead and closing this. The original surface bug is fixed anyway; the discussion is more about a nicer implementation internally.
