### ISSUE TITLE
Non-exported record fields

### ISSUE THREAD

**Issue by vkleen** [tweag/nickel#880]
Sometimes fields in a record are useful or necessary when constructing the record in Nickel, but will not be understood by downstream tools. I propose adding an annotation `not_exported` to record fields. The name is of course open to bikeshedding.

For example,
```nickel
let schema = {
    foo | {
        id | Str
           | not_exported
           | force = "${foo.id}",
        name | Str,
    },
    bar | {
        reference | Str,
    }
} in
{
    foo.name = "foobar",
    bar.reference = foo.id,
} | schema
```
should export via `nickel export` to
```json
{
  "foo": {
    "name": "foobar"
  },
  "bar": {
    "reference": "${foo.id}"
  }
}
```

The downstream tool would generate a unique `id` for `foo` and support its own string interpolation. But it would not allow `id` to be set for `foo` manually.

**Additional context**
With `not_exported` in a metavalue, it would be important for these metavalues to be attached to record fields and not to their values. Otherwise in the example above `bar.reference` wouldn't be exported either. So this feature will probablye depend on RFC005, #819.

**Comment by yannham** [comment]
Other random bikeshedding proposals:

- hidden
- local
- internal
- ignore

**Comment by aspiwack** [comment]
My understanding is that the idea is that such non-exported field would be a normal field as far as Nickel is concerned (in particular, if I name your record `baz`, then `baz.foo.id` would be well-defined), but when producing a json file, you would not serialise that field. Is this indeed the intention?

**Comment by yannham** [comment]
For the record, this [exists in CUE](https://cuelang.org/docs/tutorials/tour/types/defs/) as well, and is used heavily in my limited experience (basically any "constraint" definition or function encoding)
