### ISSUE TITLE
Special characters in quoted field identifiers should be allowed

### ISSUE THREAD

**Issue by sir4ur0n** [tweag/nickel#888]
**Describe the bug**
It is currently impossible to use a special character, e.g. `京`, in quoted type field identifiers, while it should be possible.

**To Reproduce**
```
nickel> {"fo京o" = "bar"}
{ fo京o = "bar" }
nickel> {"fo京o" = "bar"} : {"fo京o" : Str}
error: incompatible types
  ┌─ repl-input-11:1:1
  │
1 │ {"fo京o" = "bar"} : {"fo京o" : Str}
  │ ^^^^^^^^^^^^^^^^^ this expression
  │
  = The type of the expression was expected to be `{ "fo京o" : Str  , }` (a contract)
  = The type of the expression was inferred to be `{fo京o: Str}`
  = Static types and contracts are not compatible
```

**Expected behavior**
This should correctly parse and be supported.

**Environment**
 - Version of the code: `master`

**Additional context**
* Special characters are accepted in expressions, e.g. `{ "fo京o" = "bar" }`
* Special characters are accepted in contracts, e.g. `{"fo京o" = "bar"} | {"fo京o" : Str}`
* Special characters **are not accepted** in types input by users, e.g. `{"fo京o" = "bar"} : {"fo京o" : Str}`:
```
nickel> {"fo京o" = "bar"} : {"fo京o" : Str}
error: incompatible types
  ┌─ repl-input-8:1:1
  │
1 │ {"fo京o" = "bar"} : {"fo京o" : Str}
  │ ^^^^^^^^^^^^^^^^^ this expression
  │
  = The type of the expression was expected to be `{ "fo京o" : Str  , }` (a contract)
  = The type of the expression was inferred to be `{fo京o: Str}`
  = Static types and contracts are not compatible
```
* Special characters **are accepted** in types inferred/generated by Nickel, e.g.:
```
nickel> :typecheck {"fo京o" = "bar"} : _
Ok: {fo京o: Str}
```

The documentation should probably also be updated.

**Comment by matthew-healy** [comment]
Just adding my observation from Slack:

> pretty-printing the post transformation ast of `{ foo = "bar" } : { foo : Str }` gives:
> ```
> let %1 =
> (%assume% ($record { foo = $string, } $empty_tail)
>     # <label>
>     )
>   (let %0 = "bar" in { foo = %0, })
> in
> 
> %1 : {foo: Str}
> ```
>
> whereas doing the same for `{ "foo" = "bar" } : { "foo" : Str }` gives:
> ```
> let %3 =
> (%assume% (let %1 : Str  = : Str  in { foo = %1, })
>     # <label>
>     )
>   (let %2 = "bar" in { foo = %2, })
> in
> 
> %3 : let %0 : Str  = : Str  in { foo = %0, }
> ```

**Comment by yannham** [comment]
Actually it seems not even related to special characters but just to quoted field identifiers:

```
nickel> {foo = 1} : {foo : Num}
{ foo = 1 }

nickel> {foo = 1} : { "foo" : Num}
error: incompatible types
  ┌─ repl-input-1:1:1
  │
1 │ {foo = 1} : { "foo" : Num}
  │ ^^^^^^^^^ this expression
  │
  = The type of the expression was expected to be `{ foo : Num  , }`
  = The type of the expression was inferred to be `{foo: Num}`
  = These types are not compatible
```

**Comment by sir4ur0n** [comment]
From a user perspective this is only blocking for special characters, as otherwise one can use the unquoted syntax.

From a bug identification perspective, I think you are getting pretty close to the root cause :smile:

**Comment by yannham** [comment]
I think I know what is happening. A record definition, which can contain compound paths `{foo.bar.baz = 1}`, piecewise definitions `{foo.bar = 1, foo.bar = 2}`, dynamic field definitions `{"foo%{bar}" = 1}`, etc. is desugared to a simple record definition. This desugaring decides, in particular, if quoted fields are actually dynamic like `{"foo%{bar}" = 1}`, or just static like `{"foo&bar" = 1}`. In the latter case, the quotes is just a source syntax to put more characters into the name of the field, but doesn't make a difference.

However, when an expression like a record literal appears in a type position, the parser decides if it is actually a static type, or a contract (a value). This happens before said desugaring, so any quoted field is probably treated differently than a static, non-quoted field.

There are non trivial reasons for that (for example, how would you desugar `{foo.bar.baz : Str}`? Both `{foo = {bar = {baz : Str}}}` and `{foo : {bar : {baz : Str}}}` make sense, depending on the context). That being said, we can still probably factor out the "detect static string" optimization and also applies it inside the `parser::uniterm::UniRecord::into_type_strict()` function, that is the one deciding if something is a record type or not.
