### ISSUE TITLE
Recursive overriding for dictionary contracts

### ISSUE THREAD

**Issue by vkleen** [tweag/nickel#892]
## Status Quo
Currently dictionary contracts behave differently from record contracts when recursively overriding fields:
```
{
    b = {
      foo = c.foo,
    },
    c = {
    },
} | {
  _: {
    foo | Str
        | optional
        | default = "",
  }
}
```
complains about `c.foo` missing, while
```
{
    b = {
      foo = c.foo,
    },
    c = {
    },
} | {
  b | {
    foo | Str
        | optional
        | default = "",
  },
  c | {
    foo | Str
        | optional
        | default = "",
  }
}
```
yields the expected result `{ b = { foo = "" }, c = { foo = "" } }` upon evaluation.
## Proposal
We should ensure that dictionary contracts behave like record contracts with only the top-level field names being unknown. Here, @yannham suggests that the dictionary contract `{ _: C }` upon being applied generate a "scaffold" of the same shape as the record it is being applied to. I.e. `{ foo = ..., bar = ... } | { _: C }` should be equivalent to `{ foo = ..., bar = ... } | { foo | C, bar | C, .. }`.

The overall goal should be to ensure that applying a dictionary contract `{ _: C }` to a record is the same as applying `C` to each of the fields in the record.

**Comment by yannham** [comment]
Rereading this, I think it does make sense that `{foo, bar, ..} | {_ : C}` behaves the same as `{foo | C, bar | C, ..}`, for consistency.

**Comment by vkleen** [comment]
Here is another example of dictionaries not respecting recursive overriding:
```
{
  foo | Str
    | default = "blub",

  config.output.value = foo,
} & {
  foo = "Overridden",
}
```
yields `{ config = { output = { value = "Overridden" } }, foo = "Overridden" }` as expected. But as soon as I try to annotate `config` with a dictionary contract,
```
{
  config | {_: {
    value | Str,
  }},
} & {
  foo | Str
    | default = "blub",

  config.output.value = foo,
} & {
  foo = "Overridden",
}
```
I get `{ foo = "Overridden", config = { output = { value = "blub" } } }`. This is even worse than the earlier example. The contract annotation should never silently change the semantics.

**Comment by vkleen** [comment]
After playing around with it some more, my previous comment seems to not actually be related to dictionary contracts. The same thing happens if `config` gets the annotation `{ output | { value | Str } }`. Instead, this seems to be an instance of record merging currently being non-associative, with RFC005, #819, not implemented yet.

**Comment by vkleen** [comment]
My problem in https://github.com/tweag/nickel/issues/892#issuecomment-1300989418 has been resolved, probably by #990 🎉. The original complaint still stands, however.

**Comment by yannham** [comment]
Revisiting this issue, I think it's more the case than ever once #1086 lands. Then we would have an additional discrepancy with respect to when contract are applied. On the other hand, having a lazy, recursive dictionary contract would simply amounts to pushing contracts to the list of pending_contracts for each and every field, which would be very simple.

**Comment by vkleen** [comment]
I feel like this issue is really an unfortunate combination of the implementation of dictionary contracts using the `%record_map%` primop and #976. If we manage to build a record mapping function that preserves recursive thunk dependencies and implement dictionaries through that, it seems to me that this issue will magically vaporise.

**Comment by yannham** [comment]
Note that recursive mapping would still be slightly different semantically than pushing the contracts to the leaves:

```nickel
# this would pass with recursive mapping
let fst = { foo.id | default = 1} | {_ : {id | Num}} in
fst & {foo.id = "a"}

# this fails
let fst = { foo.id | Num | default = 1} in
fst & {foo.id = "a"}
```

Though, I'm not sure what should do the dictionary contract in that case. One could argue that the first one is also reasonable, in the spirit of the RFC005 part that says contracts applications happening outside of record fields don't propagate (it's not entirely true: for example, for record contracts).

A second stance is to say: dictionary contracts should really be like pushing the contract down, in which case the two examples above should behave the same.
