### ISSUE TITLE
Document `| force` metadata

### ISSUE THREAD

**Issue by sir4ur0n** [tweag/nickel#894]
**Describe the bug**
Apparently there exists a `| force` metadata, according to @matthew-healy (Slack conversation).
This is not documented in https://nickel-lang.org/user-manual/syntax/

**To Reproduce**
N/A

**Expected behavior**
All possible metadata are documented.

**Comment by vkleen** [comment]
This is part of the implementation of the merge priorities RFC001, see also #843. Are we sure yet if we plan to keep the current syntax?

**Comment by yannham** [comment]
Yes, as @vkleen said, it's a temporary syntax which still need bikeshedding. However, the manual on `master` isn't deployed on the website (which points to the `stable` branch), so we can still write this documentation with the current syntax and fix it later.

**Comment by yannham** [comment]
[Replace my previous deleted comment]
Actually, new priorities are documented in maser: https://github.com/tweag/nickel/blob/master/doc/manual/merging.md#merge-priorities. The website points to the last official version (0.2.1), which doesn't support extended merge priorities. I think it makes sense this way: if you are using the `master` version of Nickel, you should probably use the documentation on `master` as well.

**Comment by yannham** [comment]
@sir4ur0n Can I close this then, or do you still think there is some action to take?

**Comment by sir4ur0n** [comment]
I thought https://nickel-lang.org/ was automatically redeployed with `master` but it's apparently only manually redeployed when a new stable version is released, so I guess we can close it, thank you
