### ISSUE TITLE
Emacs mode

### ISSUE THREAD

**Issue by sir4ur0n** [tweag/nickel#897]
**Is your feature request related to a problem? Please describe.**
Currently editing Nickel files in Emacs is uncomfortable: there is no `nickel-mode`, so there is no syntax highlighting or smooth [LSP integration](https://emacs-lsp.github.io/lsp-mode/page/adding-new-language/).

**Describe the solution you'd like**
* A `nickel` package on [Melpa](https://melpa.org/#/)
* This package should provide a `nickel-mode` for `.ncl` files
* With that, we could document how to add LSP support for users, and we might even add Nickel to https://emacs-lsp.github.io/lsp-mode/page/languages/

**Describe alternatives you've considered**
Using another editor, but it's a big commitment (considering how developers are attached to their favorite editor :grin: )

**Additional context**
There are already VS Code and (Neo)Vim integrations in https://github.com/tweag/nickel/tree/master/lsp#interfacing-with-editors

**Comment by sir4ur0n** [comment]
Note that Emacs 29 will have native support for tree-sitter: https://www.nathanfurnal.xyz/posts/building-tree-sitter-langs-emacs/

**Comment by ebresafegaga** [comment]
Completed with [this](https://github.com/nickel-lang/nickel-mode/pull/2)
