### ISSUE TITLE
Improved contract violation error UX

### ISSUE THREAD

**Issue by matthew-healy** [tweag/nickel#917]
**Is your feature request related to a problem? Please describe.**

Currently, when a contract check fails, we provide the user with an error message describing which contract was violated, and which value caused the failure. However, this error output contains a lot of internal noise, which I hypothesise could make it difficult for newcomers to Nickel to grok the actual problem.

Consider, for example, the following program:

```ncl
let x | { a : Num } = { a = "1" } in x
```

(Note that this example was chosen for simplicity's sake - many of the points here also extend to more involved examples.)

This generates the following contract failure:

<details closed>
<summary>Hidden for brevity</summary>
<br>

```
error: contract broken by a value
   ┌─ :1:5
   │
 1 │ {a: Num}
   │     --- expected field type
   │
   ┌─ <stdlib/internals>:73:62
   │
73 │               %record_insert% f acc (%assume% contract label val)
   │                                                              ^^^ applied to this expression
   │
   ┌─ /home/matthew/projects/tweag/copies/nickel/scratchpad/e1.ncl:1:29
   │
 1 │ let x | { a : Num } = { a = "yes" } in x
   │                             ----- evaluated to this expression
   │
   ┌─ <unknown> (generated by evaluation):1:1
   │
 1 │ "yes"
   │ ----- evaluated to this value

note: 
  ┌─ /home/matthew/projects/tweag/copies/nickel/scratchpad/e1.ncl:1:9
  │
1 │ let x | { a : Num } = { a = "yes" } in x
  │         ^^^^^^^^^^^ bound here

note: 
  ┌─ <stdlib/internals>:8:23
  │
8 │   "$num" = fun l t => if %typeof% t == `Num then t else %blame% l,
  │                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ While calling to <func>

note: 
   ┌─ <stdlib/internals>:73:37
   │
73 │               %record_insert% f acc (%assume% contract label val)
   │                                     ----------------------------- (1) calling <func>
```

</details>

This error:
- Presents the failed contract free of context in the program (indeed, even the file name is missing).
- Includes a lot of internal noise which obscures the actual problem.
- Presents the callstack in an unclear way (what am I meant to take from the sections marked `note`?)
- Does not give the user any further instructions on how to fix the error or further diagnose the issue.

Contrast this with the error which we get if we replace the contract annotation with a type annotation:

<details closed>
<summary>Hidden for brevity</summary>
<br/>

```
error: incompatible rows declaration
  ┌─ /home/matthew/projects/tweag/copies/nickel/scratchpad/e1.ncl:1:23
  │
1 │ let x : { a : Num } = { a = "yes" } in x
  │                       ^^^^^^^^^^^^^ this expression
  │
  = The type of the expression was expected to be `{a: Num}`
  = The type of the expression was inferred to be `{a: Str}`
  = Could not match the two declaration of `a`

error: While typing field `a`: incompatible types
 = The type of the expression was expected to be `Num`
 = The type of the expression was inferred to be `Str`
 = These types are not compatible
```

</details>

The type error:
- Provides the file the error appears in, as well as the surrounding context for the erroneous code.
- Only includes information directly relevant to the immediate problem.

**Describe the solution you'd like**

I haven't looked into the error reporting code in detail yet, but I imagine something like the following should be feasible with the information we currently have at the point of contract violation:

<details closed>
<summary>Hidden for brevity</summary>
<br/>

```
error: contract violated by a value
   ┌─ /home/matthew/projects/tweag/copies/nickel/scratchpad/e1.ncl:1:5
   │
 1 │ let x | { a : Num } = { a = "yes" } in x 
   │         ^^^^^^^^^^^ This contract is violated
   │      
   ┌─ /home/matthew/projects/tweag/copies/nickel/scratchpad/e1.ncl:1:5
   │
 1 │ let x | { a : Num } = { a = "yes" } in x 
   │                       ^^^^^^^^^^^^^ by this value 
   │      
   = Either provide a value of the correct type, or change the contract.

callstack:

  ┌─ /home/matthew/projects/tweag/copies/nickel/scratchpad/e1.ncl:1:9
  │
1 │ let x | { a : Num } = { a = "yes" } in x
  │         ^^^^^^^^^^^ bound here

  ┌─ <stdlib/internals>:8:23
  │
8 │   "$num" = fun l t => if %typeof% t == `Num then t else %blame% l,
  │                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ While calling to <func>

   ┌─ <stdlib/internals>:73:37
   │
73 │               %record_insert% f acc (%assume% contract label val)
   │                                     ----------------------------- (1) calling <func>
```

</details>

While I think the above is already a clear improvement, I also think it could be a good idea to hide the callstack by default & allow users to opt in to it via either an environment variable (similar to `RUST_BACKTRACE`) or some sort of global Nickel configuration.

**Additional context**

<details closed>
<summary>Calling a statically-typed function from another file</summary>

Assume we have the following code, defined in `mylib.ncl`:

```ncl
{
   sumTotals : forall r r'. { total: Num; r } -> { total: Num; r' } -> Num =
    fun r r' => r.total + r'.total,
}
```

And then the calling code in `config.ncl`:

```ncl
let mylib = import "mylib.ncl" in
let first = { total = 100 } in
let second = { total = "5", other = 999 } in
mylib.sumTotals first second
```

The current error looks like this:

```
error: contract broken by the caller
   ┌─ :1:42
   │
 1 │ forall r r'. {total: Num ; r} -> {total: Num ; r'} -> Num
   │                                          --- expected type of the argument provided by the caller
   │
   ┌─ <stdlib/internals>:73:62
   │
73 │               %record_insert% f acc (%assume% contract label val)
   │                                                              ^^^ applied to this expression
   │
   ┌─ /path/to/project/config.ncl:3:24
   │
 3 │ let second = { total = "5", other' = 999 } in
   │                        -------- evaluated to this expression
   │
   ┌─ <unknown> (generated by evaluation):1:1
   │
 1 │ "5"
   │ -------- evaluated to this value
   │
   = This error may happen in the following situation:
     1. A function `f` is bound by a contract: e.g. `Num -> Num`.
     2. `f` is called with an argument of the wrong type: e.g. `f false`.
   = Either change the contract accordingly, or call `f` with an argument of the right type.
   = Note: this is an illustrative example. The actual error may involve deeper nested functions calls.

note: 
  ┌─ /path/to/project/mylib.ncl:2:15
  │
2 │   sumTotals : forall r r'. { total : Num; r } -> { total : Num; r' } -> Num =
  │               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ bound here

note: 
  ┌─ <stdlib/internals>:8:23
  │
8 │   "$num" = fun l t => if %typeof% t == `Num then t else %blame% l,
  │                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ While calling to t

note: 
   ┌─ <stdlib/internals>:73:37
   │
73 │               %record_insert% f acc (%assume% contract label val)
   │                                     ----------------------------- (1) calling <func>

note: 
   ┌─ <stdlib/internals>:24:47
   │
24 │           (fun x => %assume% t (%go_codom% l) (e (%assume% s (%chng_pol% (%go_dom% l)) x)))
   │                                               -------------------------------------------- (2) calling e

note: 
   ┌─ <stdlib/internals>:24:21
   │
24 │           (fun x => %assume% t (%go_codom% l) (e (%assume% s (%chng_pol% (%go_dom% l)) x)))
   │                     ---------------------------------------------------------------------- (3) calling <func>

note: 
   ┌─ <stdlib/internals>:24:21
   │
24 │           (fun x => %assume% t (%go_codom% l) (e (%assume% s (%chng_pol% (%go_dom% l)) x)))
   │                     ---------------------------------------------------------------------- (4) calling <func>
```

This could be better-presented as something like:

```
error: contract violated by caller
   ┌─ /path/to/project/mylib.ncl:1:42
   │
 2 │ sumTotals : forall r r'. {total: Num ; r} -> {total: Num ; r'} -> Num = ...
   │                                                      ^^^ Expected type of the argument
   │
   ┌─ /path/to/project/config.ncl:3:24
   │
 3 │ let second = { total = "5", other' = 999 } in
   │                        ^^^^ Value provided by the caller
   │
   = This error may happen in the following situation:
     1. A function `f` is bound by a contract: e.g. `Num -> Num`.
     2. `f` is called with an argument of the wrong type: e.g. `f false`.
   = Either call the function with an argument of the right type, or change the
     contract accordingly.
   = Note: this is an illustrative example. The actual error may involve deeper 
     nested functions calls.

callstack:

  ┌─ /path/to/project/mylib.ncl:2:15
  │
2 │   sumTotals : forall r r'. { total : Num; r } -> { total : Num; r' } -> Num =
  │               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ bound here

  ┌─ <stdlib/internals>:8:23
  │
8 │   "$num" = fun l t => if %typeof% t == `Num then t else %blame% l,
  │                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ While calling to t

   ┌─ <stdlib/internals>:73:37
   │
73 │               %record_insert% f acc (%assume% contract label val)
   │                                     ----------------------------- (1) calling <func>

   ┌─ <stdlib/internals>:24:47
   │
24 │           (fun x => %assume% t (%go_codom% l) (e (%assume% s (%chng_pol% (%go_dom% l)) x)))
   │                                               -------------------------------------------- (2) calling e

   ┌─ <stdlib/internals>:24:21
   │
24 │           (fun x => %assume% t (%go_codom% l) (e (%assume% s (%chng_pol% (%go_dom% l)) x)))
   │                     ---------------------------------------------------------------------- (3) calling <func>

   ┌─ <stdlib/internals>:24:21
   │
24 │           (fun x => %assume% t (%go_codom% l) (e (%assume% s (%chng_pol% (%go_dom% l)) x)))
   │                     ---------------------------------------------------------------------- (4) calling <func>
```

</details>

**Comment by yannham** [comment]
General remarks:

- dynamic error reporting in a lazy language is in some ways much harder than static error reporting, because the point where we raise the error may have lost context and evaluated a lot of things away. While the comparison is useful, we must keep in mind that we won't necessary be on par with static error reporting, in particular with respect to locations. On the other hand, we have other useful information at runtime that static typing doesn't have (mainly "witnesses", or the concrete values which violates a contract).
- The first line of the original error is different from your suggestion. Note that only the `Num` part is underlined. What it prints is what part of the contract has been violated: we just reuse the framework of error reporting to handle the formatting, hence the strange missing filename and lines, but ideally it wouldn't have those at all (in that, those are spurious decorations, we don't actually miss context). For example, see the difference on a function contract violation:
    ```
    nickel> let ev_ev : ((Num -> Num) -> Num) -> Num = fun ev => ev (fun x => x + 1) in
    ev_ev (fun f => f "a")

      error: contract broken by the caller
       ┌─ :1:3
       │
     1 │ ((Num -> Num) -> Num) -> Num
       │   --- expected type of the argument provided by the caller
    ```

   This is arguably more information that just the original contract, which is shown as:

    ````
    1 │ let ev_ev : ((Num -> Num) -> Num) -> Num = fun ev => ev (fun x => x + 1) in
      │             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ bound here
    ````

    That being said, we may group the two information together, to underline the right part of the type in its original context.
- One possible trap is to focus on very simple contract violations. As soon as several nested function are involved, things get messier. It's hard to filter through a callstack of lazy language to decide what is relevant (you can see `eval::callstack::CallStack::group_by_calls` for example) and in some cases we do need the information. Not to say that the current implementation is optimal: quite the contrary, and I would gladly see some effort to think harder about errors and error reporting, as they are absolutely fundamental. They are the final, concrete vehicle for all the additional correctness that Nickel brings with types and contracts. If error message are bad, then contracts are plain useless. But we must be careful of not making slightly more involved errors much harder to solve.

**Comment by matthew-healy** [comment]
> What it prints is what part of the contract has been violated: we just reuse the framework of error reporting to handle the formatting, hence the strange missing filename and lines, but ideally it wouldn't have those at all (in that, those are spurious decorations, we don't actually miss context).

Ah, TIL! In that case, maybe just removing those bits entirely would already be an improvement.

> we may group the two information together, to underline the right part of the type in its original context

This sounds like a really good idea to me. The intention definitely isn't to lose any information - my ideas above should really just be considered very rough sketches (especially as I haven't really dug into the error reporting code in any great detail yet).

**Comment by yannham** [comment]
Unless I'm misunderstanding, I think #1139 is just one part of the answer to this issue. Matthew made other points than just hiding stacktraces from the stdlib, like grouping the last note and the initial "subcontract" underlining.

**Comment by ebresafegaga** [comment]
Right. I didn't remove the  "Closes ..." part from the pull request description 👍
