### ISSUE TITLE
Support infinity numbers

### ISSUE THREAD

**Issue by sir4ur0n** [tweag/nickel#930]
**Is your feature request related to a problem? Please describe.**
Nickel currently does not permit to generate any YAML value.
In YAML, + and - infinity numbers are legal: https://yaml.org/type/float.html

**Describe the solution you'd like**
Nickel `Number` type should support + and - infinity. I don't have any strong opinion on the syntax.

**Describe alternatives you've considered**
N/A

**Comment by thufschmitt** [comment]
Dunno about the syntax, but it looks like Nickel internally supports that:

```console
$ echo "foo: .inf" > foo.yaml
$ echo '(import "foo.yaml").foo - 1' > foo.ncl
$ nickel -f foo.ncl  
inf
```

**Comment by yannham** [comment]
Internally, floats are `f64`, so they do support infinity and NaN indeed, there's just no syntax for it.

**Comment by yannham** [comment]
Or maybe just something like `number.infinity` in the stdlib? That would still require a new primp op `%infinity%`, but no new surface syntax
