### ISSUE TITLE
Rationale: Why is Nickel not a DSL written in Haskell

### ISSUE THREAD

**Issue by fricklerhandwerk** [tweag/nickel#931]
I’m missing from the [rationale](https://github.com/tweag/nickel/blob/master/RATIONALE.md) the answer to the following question:

> Why not use a DSL from within Haskell instead?

Haskell is a well-established language that has all the features Nickel strives towards (prominently: types, contracts, and effects) but also all the developer tooling and a sufficiently large community of software developers _and_ language researchers. Most importantly, one of Haskell’s purposes is to act as a framework for DSLs.

Wouldn’t it be much cheaper to make Nickel a Haskell DSL?

**Comment by yannham** [comment]
Using an existing language to embed configuration is indeed a reasonable approach. This is a bit different from a full fledged DSL, but Pulumi is doing something similar, to leverage your known and well-equipped language of choice to write a configuration (after all, it's a library, and libraries are restricted form of DSLs).

Beside typechecking, Nix (the language) itself could also be itself the host of configuration DSL. This is in fact exactly what Nixpkgs and NixOS modules are, a DSL embedded into the Nix language.

While it brings obvious advantages, I can also see some issues.

## Error messages

The end result of Nickel being a useful tool are, all in all, error messages (not only, but really, it's the user-facing consequence of the majority of advanced features: typechecking and contracts). It doesn't help to have a very fancy type system or advanced contracts if you're unable to diagnose when something goes wrong (which is, often, hard in Nix). To me, the biggest issue would be that Haskell error messages would probably be awful. They can already be bad for normal Haskell, but if we are to embed things such as row polymorphism in Haskell using type-class hackery, ooch. I also don't know how to encode the interaction between the type and the contract system, that is gradual typing, in a usable way.

The contract system alone could be easily implemented in any functional language without much native support (including Nix). Once again, the big difference we hope to make is, beside naturality of the syntax, LSP support and so on, is in error messages. Being builtins, contract error reporting has special support, such as tracking thunks on the stack to get the evaluated expression that made a contract fail, has access to source positions, and so on. This is much harder to replicate in a host language.

## LSP integration

It's more or less the same point, but for LSP. Thanks to @ebresafegaga, we get more and more nice things in the Nickel LSP, like record completion based on both type information, contract information, and bare record structures. This is the kind of feature that may make using Nickel for e.g. Terraform very appealing: even if you don't care about functions and additional safety of the language, if you get completion with documentation as you type, this is already probably way better than your current experience. With a Haskell DSL, it's close to impossible (well, even the LSP experience for pure Haskell is not the best, in my limited experience).

## Haskell is heavy

One of the possible use-case of Nickel would be to embed it, either as binary, or linked to it as a C library, for bigger tools to use (think a Terraform clone for example). If you need to pull all of the GHC toolchain to evaluate your 100 lines of configuration, good luck. Garbage collection and Haskell runtime makes it also harder to interface it easily with other languages and binary tools.

## Haskell is not familiar

Another goal of Nickel is to be understandable by DevOps, not only by functional programmers. In particular, as long as you don't write library code yourself, the syntax is quite JSON-like, and doesn't use very fancy constructions (contracts are often specified externally to the configuration itself). The goal is that changing some configuration option should be trivial to do for non-developers. Now, with a Haskell DSL, it's another matter, I think.

## Is it really less work?

A big part of the work on developing Nickel is around language design and exploration. I think implementing the core language from scratch, now that we know what it looks like, wouldn't be that of a huge task. Another part is developing the tooling, and that we could get some for free, but I think that the Haskell tooling would be close to useless for such an advanced DSL anyway, as mentioned for error messages and LSP for example. Also, embedding Nickel in Haskell would probably involve constraints and work that we don't have right now (such as embedding the type system of Nickel inside the one of Haskell). It's hard to tell, but I wouldn't be so sure that doing so would be much cheaper.

**Comment by fricklerhandwerk** [comment]
Thanks for this great reply! This should go straight to the rationale document.
