### ISSUE TITLE
Destructuring doesn't preserve types

### ISSUE THREAD

**Issue by matthew-healy** [tweag/nickel#933]
**Describe the bug**

This program does not typecheck:

```ncl
let x : { a : Num } = { a = 1 } in 
let { a } = x in
a : Num 
```

`a`'s type is inferred to be `Dyn`.

**Expected behavior**

Destructuring should preserve existing type information, so `a` should have type `Num`.

**Comment by matthew-healy** [comment]
Yes, #1099 leaves part of this unsolved. In particular in an example like this:

```
let r = { a = 1 } in
let { a : Str } = r in
a
```

we currently get a runtime contract error rather than a static typechecking error. Though actually, now that the first part of RFC005 is merged this is probably something that can be fixed pretty soon. 

Happy to also split that out into another issue if that's easier.

**Comment by yannham** [comment]
What is your plan about the last example? In fact I'm not sure we've decided somewhere what is the semantics of using a type annotation on the left hand side of a pattern (but there's nothing wrong deciding it now!)

Would that be that `let { a : Str } = r in` is typechecked the same as `let a = (r : {a : Str})`? What would be the algorithm? Another question is what to do with mixed type and contract annotations. That is:

```
let { a : Str, bar | CustomContract, foo = {bar = {baz : Num, baz' | CustomContract}}} = r in
```

Should we:

1. Not typecheck anything. As when using a record as a type annotation , either it's a record type, either it's considered as a whole as a custom contract.
2. Extract the "strict" part of the pattern, something like `{a : Str, foo: {bar: {baz : Num; _a}}; _b}` and typecheck `r` against it? In the spirit of "typecheck the destructuring as you would typecheck the corresponding desugaring"

In any case, I don't know if it's an really important matter right now. The original issue is that "you can't use destructuring inside statically typed code", which I think has been solved. It's probably better to open another issue to discuss what should be the semantics of type annotations outside of statically typed block.

**Comment by yannham** [comment]
Wait, I think I misunderstood the situation. In fact, currently, the typechecker doesn't use any annotation even in strict mode. It means that something like:

```
(fun {x : Num} => (x : Str)) : _
```

currently typechecks. Which is indeed problematic. Let's keep the issue open until this is solved.

**Comment by matthew-healy** [comment]
Yeah, that example was exactly my point. I think as a first pass we should just be able to statically raise mismatches like this one. I couldn't do it previously as I wanted to wait for your refactoring of MetaValue to land, as it seemed likely to change how this would ultimately work. Plus in the current state we at least get a contract failure from the mismatch.

I'm going to work on catching this statically on Friday, and once that's done I'll close this issue.
