### ISSUE TITLE
Improve typing of record.fields and record.values to take a dictionary type

### ISSUE THREAD

**Issue by yannham** [tweag/nickel#936]
**Is your feature request related to a problem? Please describe.**
The current typing of `record.fields` and `record.values` is the following:

```nickel
nickel> :query record.fields
• contract: { ; Dyn} -> Array Str

nickel> :query record.values
• contract: { ; Dyn} -> Array Dyn
```

The type for `record.values` is losing information, because we know that if all fields of the input record are the same (when used e.g. as a dictionary), then the output values have this type as well. But right now, everything is `Dyn`.

What's more, this type is useless in statically typed code, because there is no way to construct values of type `{; Dyn}`. Dynamically, this contract is essentially the same as `{..}`, and we should probably get rid of it. Or, a second approach could be to allow the type of the tail to be anything, and define `{_ : T} := {; T}`.

But right now, this type feels redundant, and useless statically. We propose to rather use dictionary types `{_ : T}`, which  accept some values.

**Describe the solution you'd like**
The aforementioned functions to have the following signature:

- `fields : forall a. {_ : a} -> Array Str`
- `values: forall a. {_ : a} -> Array a`

**Comment by vkleen** [comment]
This typing of `values` would already prevent using it for the record in the documentation example `{ one = 1, world = "world" }`. I think it would make more sense to keep dynamically typed (that is, untyped) `record.values` and `record.fields` and add other functions `values'` and `fields'` (naming open to bikeshedding, of course) that propagate the additional information available for dictionary types.

**Comment by yannham** [comment]
> This typing of values would already prevent using it for the record in the documentation example { one = 1, world = "world" }

Unless I'm mistaken, it's still a strictly better option to use `forall a. {_ : a } -> Array a`. It works for dictionaries whenever `a` is more precise that `Dyn` (and one could argue that in statically typed code, `Dyn` is annoying to deal with anyway, as long as we haven't implemented RFC004), and dynamically it's accepting the same things as `{; Dyn} -> Array Dyn`.

**Comment by yannham** [comment]
Put differently, `{; Dyn} -> Array Dyn` is morally the same as `{_ : Dyn} -> Array Dyn` which is one instantiation of `forall a. {_ : a} -> Array a`, so the latter type should be strictly more general.
