### ISSUE TITLE
Recompute the linearization of a file when it any of the file it imports changes (and is relinearized)

### ISSUE THREAD

**Issue by ebresafegaga** [tweag/nickel#951]
This would be a further improvement on #932

**Comment by yannham** [comment]
I think currently the cache is doing the wrong thing, like only relying the timestamp of the current file, and not transitively on the imports. It hasn't been a problem until now between during normal evaluation, or in the REPL, we just append new imports, but this may become a problem within the REPL when supporting imports

**Comment by ebresafegaga** [comment]
Actually, the cache does handles this correctly because of the way completion for import terms works.  See #993

**Comment by ebresafegaga** [comment]
> I think currently the cache is doing the wrong thing, like only relying the timestamp of the current file, and not transitively on the imports

You're right. And this is the cause of [this issue](https://github.com/tweag/nickel/pull/1037#issuecomment-1381645916)

**Comment by jneem** [comment]
Transitive dependencies are now invalidated. Any specific bugs with that invalidation can get their own issue.
