### ISSUE TITLE
Get rid of `import-cargo`

### ISSUE THREAD

**Issue by sir4ur0n** [tweag/nickel#967]
Follow-up of https://github.com/tweag/nickel/pull/963

This PR migrated the `nickel` build from `import-cargo` to `crane`, but the WASM build variant was not yet migrated, to keep the PR bite-sized.

This issue tracks getting rid "for good" of `import-cargo`.

With a bit of luck, this should be as simple as replacing `cargoHome` with `(mkCraneArtifacts {inherit rust;}).cargoArtifacts`

**Comment by yannham** [comment]
For the record, I gave a quick try at that. Applying @sir4ur0n's suggestion, I first got a strange permission denied error:

```
error: builder for '/nix/store/kjpsw58l7qg13h277wkv08k47rbl7xvi-nickel-wasm-0.3.1_20221216_dirty.drv' failed with exit code 1;
       last 10 log lines:
       > no configure script, doing nothing
       > building
       > Error: Error during execution of `cargo metadata`: error: failed to get `ansi_term` as a dependency of package `nickel-lang v0.3.1 (/build/source)`
       >
       > Caused by:
       >   failed to create directory `/homeless-shelter/.cargo/registry/index/github.com-1ecc6299db9ec823`
       >
       > Caused by:
       >   Permission denied (os error 13)
       >
       For full logs, run 'nix log /nix/store/kjpsw58l7qg13h277wkv08k47rbl7xvi-nickel-wasm-0.3.1_20221216_dirty.drv'.
```

Following https://github.com/NixOS/nix/issues/670, I added the following line at the beginning of the build phase:

```
export HOME=$(pwd)
```

Now, I get:

```nickel-wasm> Error: Error during execution of `cargo metadata`:     Updating crates.io index
nickel-wasm> warning: spurious network error (2 tries remaining): failed to resolve address for github.com: Temporary failure in name resolution; class=Net (12)
nickel-wasm> warning: spurious network error (1 tries remaining): failed to resolve address for github.com: Temporary failure in name resolution; class=Net (12)
nickel-wasm> error: Unable to update registry `crates-io`
nickel-wasm> Caused by:
nickel-wasm>   failed to fetch `https://github.com/rust-lang/crates.io-index`
nickel-wasm> Caused by:
nickel-wasm>   network failure seems to have happened
nickel-wasm>   if a proxy or similar is necessary `net.git-fetch-with-cli` may help here
nickel-wasm>   https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli
nickel-wasm> Caused by:
nickel-wasm>   failed to resolve address for github.com: Temporary failure in name resolution; class=Net (12)
error: builder for '/nix/store/v3b26xc1j324z36j990z4pvhd2qh92qi-nickel-wasm-0.3.1_20221216_dirty.drv' failed with exit code 1;
       last 10 log lines:
       >   failed to fetch `https://github.com/rust-lang/crates.io-index`
       >
       > Caused by:
       >   network failure seems to have happened
       >   if a proxy or similar is necessary `net.git-fetch-with-cli` may help here
       >   https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli
       >
       > Caused by:
       >   failed to resolve address for github.com: Temporary failure in name resolution; class=Net (12)
       >
       For full logs, run 'nix log /nix/store/v3b26xc1j324z36j990z4pvhd2qh92qi-nickel-wasm-0.3.1_20221216_dirty.drv'.
```

I think it's like there no crates available, so something is going wrong with using `crane`. It may be that we brutally redefine the `buildPhase`, but in any case, this unfortunately requires a bit more investigation.

**Comment by sir4ur0n** [comment]
The error makes me think you need to massage a bit more the crane artifacts into `wasm-pack`.
I suspect `wasm-pack` (which uses Cargo under the hood, right?) does not "see" those artifacts, thus tries to recompile the Cargo dependencies.

You probably need to "pass" or "link" the Crane artifacts path to `wasm-pack` (its underlying Cargo). I guess by setting an env var?

**Comment by yannham** [comment]
Following https://github.com/ipetkov/crane/discussions/193#discussioncomment-4473163, I managed to get `wasm-pack` start to compile, but I now have a strange "Permission denied (os error 13)" caused by custom builds scripts of dependencies (serde, typenum, etc.):

```
nickel-lang> ++ command cargo --version
nickel-lang> cargo 1.65.0 (4bc8f24d3 2022-10-20)
nickel-lang> [Nix build script] Running wasm-pack
nickel-lang> [INFO]: Checking for the Wasm target...
nickel-lang> [INFO]: Compiling to Wasm...
nickel-lang>    Compiling syn v1.0.95
nickel-lang>    Compiling cfg-if v1.0.0
nickel-lang>    Compiling typenum v1.15.0
nickel-lang>    Compiling serde v1.0.137
nickel-lang> error: failed to run custom build command for `typenum v1.15.0`
nickel-lang> Caused by:
nickel-lang>   could not execute process `/build/source/target/release/build/typenum-6ba44e225a51239a/build-script-main` (never executed)
nickel-lang> Caused by:
nickel-lang>   Permission denied (os error 13)
nickel-lang> warning: build failed, waiting for other jobs to finish...
nickel-lang> error: failed to run custom build command for `serde v1.0.137`
nickel-lang> Caused by:
nickel-lang>   could not execute process `/build/source/target/release/build/serde-01a59449dfd038a1/build-script-build` (never executed)
nickel-lang> Caused by:
nickel-lang>   Permission denied (os error 13)
nickel-lang> Error: Compiling your crate to WebAssembly failed
nickel-lang> Caused by: failed to execute `cargo build`: exited with exit status: 101
nickel-lang>   full command: "cargo" "build" "--lib" "--release" "--target" "wasm32-unknown-unknown" "--no-default-features" "--frozen" "--offline"
```
