### ISSUE TITLE
LSP server should provide completion based on contract/type context

### ISSUE THREAD

**Issue by ebresafegaga** [tweag/nickel#995]
Say we have the following program, with the cursor represented as `[.]`: 
```
{
[.]
} | SchemaFromNix
```
We should be able to get completion based on the field names from the `SchemaFromNix` contract (or maybe type)

**Comment by yannham** [comment]
If possible, that would be also great if

```
let Schema = {foo.bar | Num} in
{
 foo = {
   [.]
} | Schema
```

proposes `bar` for completion. It depends on how unclosed records are parsed. Or maybe we can focus on records that are closed. We could then go up the completion to find all the enclosing records and check if one has a schema that correspond to the subrecord we are writing down.

**Comment by ebresafegaga** [comment]
The closing record brace for the record bound to `foo` is absent. Is this intentional?

**Comment by vkleen** [comment]
For tf-ncl, I'm dealing with contracts like in [contract.ncl](https://github.com/tweag/nickel/files/10448537/contract.txt) (uploaded with `txt` extension instead of `ncl` because GitHub is being weird). I'm using them like
```nickel
let Tf = import "./contract.ncl" in
{
  config = {
    data.dhall.my_dhall_resource = {
      life[.]
    }
  }
} | Tf.Config
```
and I would like completion inforatmion at the indicated position.

**Comment by ebresafegaga** [comment]
@vkleen  Would it also be useful for this to work on type annotations? 
```
{

    foo = "",
    bar = "",
    oth[.]
    
} : { foo: Str, bar: Str, other : {a: Num, b: Num} }
```
